[hls]
relative_roots=/home/oldak/Binary-CNN-Accelerator/hls_kernel/hls_component
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=kernel/VITIS_LOOP_299_1 
syn.directive.pipeline=kernel/OUT_STREAM 
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=conv2d_l1/INIT_KH  
syn.directive.loop_flatten=conv2d_l1/INIT_FH  
syn.directive.loop_flatten=conv2d_l2/L2_KH  
syn.directive.loop_flatten=conv2d_l2/L2_FH  
syn.directive.loop_flatten=conv2d_l3/L3_KH  
syn.directive.loop_flatten=conv2d_l3/L3_FH  
syn.directive.loop_flatten=conv2d_l4/L4_KH  
syn.directive.loop_flatten=conv2d_l4/L4_FH  


