// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module kernel_conv2d_l3_Pipeline_L3_FH_L3_FW (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln139,
        output_0_address0,
        output_0_ce0,
        output_0_we0,
        output_0_d0,
        output_1_address0,
        output_1_ce0,
        output_1_we0,
        output_1_d0,
        output_2_address0,
        output_2_ce0,
        output_2_we0,
        output_2_d0,
        output_3_address0,
        output_3_ce0,
        output_3_we0,
        output_3_d0,
        output_4_address0,
        output_4_ce0,
        output_4_we0,
        output_4_d0,
        output_5_address0,
        output_5_ce0,
        output_5_we0,
        output_5_d0,
        output_6_address0,
        output_6_ce0,
        output_6_we0,
        output_6_d0,
        output_7_address0,
        output_7_ce0,
        output_7_we0,
        output_7_d0,
        output_8_address0,
        output_8_ce0,
        output_8_we0,
        output_8_d0,
        output_9_address0,
        output_9_ce0,
        output_9_we0,
        output_9_d0,
        output_10_address0,
        output_10_ce0,
        output_10_we0,
        output_10_d0,
        output_11_address0,
        output_11_ce0,
        output_11_we0,
        output_11_d0,
        output_12_address0,
        output_12_ce0,
        output_12_we0,
        output_12_d0,
        output_13_address0,
        output_13_ce0,
        output_13_we0,
        output_13_d0,
        buffer_1_address0,
        buffer_1_ce0,
        buffer_1_we0,
        buffer_1_d0,
        buffer_1_q0,
        buffer_1_address1,
        buffer_1_ce1,
        buffer_1_we1,
        buffer_1_d1,
        buffer_1_q1,
        buffer_0_address0,
        buffer_0_ce0,
        buffer_0_we0,
        buffer_0_d0,
        buffer_0_q0,
        buffer_0_address1,
        buffer_0_ce1,
        buffer_0_we1,
        buffer_0_d1,
        buffer_0_q1,
        sext_ln149,
        select_ln139
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [8:0] zext_ln139;
output  [8:0] output_0_address0;
output   output_0_ce0;
output   output_0_we0;
output  [0:0] output_0_d0;
output  [8:0] output_1_address0;
output   output_1_ce0;
output   output_1_we0;
output  [0:0] output_1_d0;
output  [8:0] output_2_address0;
output   output_2_ce0;
output   output_2_we0;
output  [0:0] output_2_d0;
output  [8:0] output_3_address0;
output   output_3_ce0;
output   output_3_we0;
output  [0:0] output_3_d0;
output  [8:0] output_4_address0;
output   output_4_ce0;
output   output_4_we0;
output  [0:0] output_4_d0;
output  [8:0] output_5_address0;
output   output_5_ce0;
output   output_5_we0;
output  [0:0] output_5_d0;
output  [8:0] output_6_address0;
output   output_6_ce0;
output   output_6_we0;
output  [0:0] output_6_d0;
output  [8:0] output_7_address0;
output   output_7_ce0;
output   output_7_we0;
output  [0:0] output_7_d0;
output  [8:0] output_8_address0;
output   output_8_ce0;
output   output_8_we0;
output  [0:0] output_8_d0;
output  [8:0] output_9_address0;
output   output_9_ce0;
output   output_9_we0;
output  [0:0] output_9_d0;
output  [8:0] output_10_address0;
output   output_10_ce0;
output   output_10_we0;
output  [0:0] output_10_d0;
output  [8:0] output_11_address0;
output   output_11_ce0;
output   output_11_we0;
output  [0:0] output_11_d0;
output  [8:0] output_12_address0;
output   output_12_ce0;
output   output_12_we0;
output  [0:0] output_12_d0;
output  [8:0] output_13_address0;
output   output_13_ce0;
output   output_13_we0;
output  [0:0] output_13_d0;
output  [8:0] buffer_1_address0;
output   buffer_1_ce0;
output   buffer_1_we0;
output  [31:0] buffer_1_d0;
input  [31:0] buffer_1_q0;
output  [8:0] buffer_1_address1;
output   buffer_1_ce1;
output   buffer_1_we1;
output  [31:0] buffer_1_d1;
input  [31:0] buffer_1_q1;
output  [8:0] buffer_0_address0;
output   buffer_0_ce0;
output   buffer_0_we0;
output  [31:0] buffer_0_d0;
input  [31:0] buffer_0_q0;
output  [8:0] buffer_0_address1;
output   buffer_0_ce1;
output   buffer_0_we1;
output  [31:0] buffer_0_d1;
input  [31:0] buffer_0_q1;
input  [15:0] sext_ln149;
input  [3:0] select_ln139;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln174_fu_404_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [3:0] select_ln139_read_reg_673;
wire    ap_block_pp0_stage0_11001;
wire  signed [31:0] sext_ln149_cast_fu_382_p1;
reg  signed [31:0] sext_ln149_cast_reg_682;
wire   [2:0] select_ln174_fu_469_p3;
reg   [2:0] select_ln174_reg_691;
wire   [2:0] select_ln174_1_fu_477_p3;
reg   [2:0] select_ln174_1_reg_697;
wire   [1:0] trunc_ln178_fu_485_p1;
reg   [1:0] trunc_ln178_reg_702;
wire   [31:0] select_ln182_fu_561_p3;
reg   [31:0] select_ln182_reg_727;
reg   [31:0] select_ln182_reg_727_pp0_iter3_reg;
wire   [31:0] select_ln182_1_fu_575_p3;
reg   [31:0] select_ln182_1_reg_733;
reg   [0:0] tmp_reg_739;
wire   [63:0] zext_ln178_fu_497_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln180_fu_549_p1;
wire   [63:0] zext_ln184_2_fu_606_p1;
reg   [2:0] ow_fu_116;
wire   [2:0] add_ln175_fu_503_p2;
wire    ap_loop_init;
reg   [2:0] oh_fu_120;
reg   [4:0] indvar_flatten6_fu_124;
wire   [4:0] add_ln174_1_fu_410_p2;
reg   [4:0] ap_sig_allocacmp_indvar_flatten6_load;
reg    buffer_0_ce1_local;
reg    buffer_0_we1_local;
reg    buffer_0_ce0_local;
reg    buffer_0_we0_local;
reg    buffer_1_ce1_local;
reg    buffer_1_we1_local;
reg    buffer_1_ce0_local;
reg    buffer_1_we0_local;
reg    output_12_we0_local;
wire   [0:0] xor_ln25_fu_623_p2;
reg    output_12_ce0_local;
reg    output_11_we0_local;
reg    output_11_ce0_local;
reg    output_10_we0_local;
reg    output_10_ce0_local;
reg    output_9_we0_local;
reg    output_9_ce0_local;
reg    output_8_we0_local;
reg    output_8_ce0_local;
reg    output_7_we0_local;
reg    output_7_ce0_local;
reg    output_6_we0_local;
reg    output_6_ce0_local;
reg    output_5_we0_local;
reg    output_5_ce0_local;
reg    output_4_we0_local;
reg    output_4_ce0_local;
reg    output_3_we0_local;
reg    output_3_ce0_local;
reg    output_2_we0_local;
reg    output_2_ce0_local;
reg    output_1_we0_local;
reg    output_1_ce0_local;
reg    output_0_we0_local;
reg    output_0_ce0_local;
reg    output_13_we0_local;
reg    output_13_ce0_local;
wire   [0:0] icmp_ln175_fu_463_p2;
wire   [2:0] add_ln174_fu_457_p2;
wire   [4:0] add_ln_fu_489_p3;
wire   [4:0] tmp_s_fu_519_p3;
wire   [4:0] zext_ln175_fu_540_p1;
wire   [4:0] or_ln_fu_530_p3;
wire   [4:0] add_ln180_fu_543_p2;
wire   [0:0] icmp_ln182_fu_555_p2;
wire   [0:0] icmp_ln182_1_fu_569_p2;
wire   [0:0] icmp_ln182_2_fu_583_p2;
wire   [31:0] mx_fu_587_p3;
wire   [31:0] val_fu_593_p2;
wire   [8:0] grp_fu_642_p4;
wire   [4:0] grp_fu_642_p0;
wire   [2:0] grp_fu_642_p1;
wire   [4:0] grp_fu_642_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [5:0] grp_fu_642_p00;
wire   [5:0] grp_fu_642_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ow_fu_116 = 3'd0;
#0 oh_fu_120 = 3'd0;
#0 indvar_flatten6_fu_124 = 5'd0;
#0 ap_done_reg = 1'b0;
end

kernel_ama_addmuladd_5ns_3ns_5ns_9s_9_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 5 ),
    .din3_WIDTH( 9 ),
    .dout_WIDTH( 9 ))
ama_addmuladd_5ns_3ns_5ns_9s_9_4_1_U296(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_642_p0),
    .din1(grp_fu_642_p1),
    .din2(grp_fu_642_p2),
    .din3(zext_ln139),
    .ce(1'b1),
    .dout(grp_fu_642_p4)
);

kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln174_fu_404_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten6_fu_124 <= add_ln174_1_fu_410_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_124 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            oh_fu_120 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            oh_fu_120 <= select_ln174_1_fu_477_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ow_fu_116 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ow_fu_116 <= add_ln175_fu_503_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        select_ln174_1_reg_697 <= select_ln174_1_fu_477_p3;
        select_ln174_reg_691 <= select_ln174_fu_469_p3;
        sext_ln149_cast_reg_682 <= sext_ln149_cast_fu_382_p1;
        trunc_ln178_reg_702 <= trunc_ln178_fu_485_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        select_ln182_1_reg_733 <= select_ln182_1_fu_575_p3;
        select_ln182_reg_727 <= select_ln182_fu_561_p3;
        select_ln182_reg_727_pp0_iter3_reg <= select_ln182_reg_727;
        tmp_reg_739 <= val_fu_593_p2[32'd31];
    end
end

always @ (*) begin
    if (((icmp_ln174_fu_404_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_124;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_0_ce0_local = 1'b1;
    end else begin
        buffer_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_0_ce1_local = 1'b1;
    end else begin
        buffer_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_0_we0_local = 1'b1;
    end else begin
        buffer_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_0_we1_local = 1'b1;
    end else begin
        buffer_0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_1_ce0_local = 1'b1;
    end else begin
        buffer_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_1_ce1_local = 1'b1;
    end else begin
        buffer_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_1_we0_local = 1'b1;
    end else begin
        buffer_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_1_we1_local = 1'b1;
    end else begin
        buffer_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        output_0_ce0_local = 1'b1;
    end else begin
        output_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (select_ln139_read_reg_673 == 4'd0))) begin
        output_0_we0_local = 1'b1;
    end else begin
        output_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        output_10_ce0_local = 1'b1;
    end else begin
        output_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (select_ln139_read_reg_673 == 4'd10))) begin
        output_10_we0_local = 1'b1;
    end else begin
        output_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        output_11_ce0_local = 1'b1;
    end else begin
        output_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (select_ln139_read_reg_673 == 4'd11))) begin
        output_11_we0_local = 1'b1;
    end else begin
        output_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        output_12_ce0_local = 1'b1;
    end else begin
        output_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (select_ln139_read_reg_673 == 4'd12))) begin
        output_12_we0_local = 1'b1;
    end else begin
        output_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        output_13_ce0_local = 1'b1;
    end else begin
        output_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & ((select_ln139_read_reg_673 == 4'd13) | ((select_ln139_read_reg_673 == 4'd14) | (select_ln139_read_reg_673 == 4'd15))))) begin
        output_13_we0_local = 1'b1;
    end else begin
        output_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        output_1_ce0_local = 1'b1;
    end else begin
        output_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (select_ln139_read_reg_673 == 4'd1))) begin
        output_1_we0_local = 1'b1;
    end else begin
        output_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        output_2_ce0_local = 1'b1;
    end else begin
        output_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (select_ln139_read_reg_673 == 4'd2))) begin
        output_2_we0_local = 1'b1;
    end else begin
        output_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        output_3_ce0_local = 1'b1;
    end else begin
        output_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (select_ln139_read_reg_673 == 4'd3))) begin
        output_3_we0_local = 1'b1;
    end else begin
        output_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        output_4_ce0_local = 1'b1;
    end else begin
        output_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (select_ln139_read_reg_673 == 4'd4))) begin
        output_4_we0_local = 1'b1;
    end else begin
        output_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        output_5_ce0_local = 1'b1;
    end else begin
        output_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (select_ln139_read_reg_673 == 4'd5))) begin
        output_5_we0_local = 1'b1;
    end else begin
        output_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        output_6_ce0_local = 1'b1;
    end else begin
        output_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (select_ln139_read_reg_673 == 4'd6))) begin
        output_6_we0_local = 1'b1;
    end else begin
        output_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        output_7_ce0_local = 1'b1;
    end else begin
        output_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (select_ln139_read_reg_673 == 4'd7))) begin
        output_7_we0_local = 1'b1;
    end else begin
        output_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        output_8_ce0_local = 1'b1;
    end else begin
        output_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (select_ln139_read_reg_673 == 4'd8))) begin
        output_8_we0_local = 1'b1;
    end else begin
        output_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        output_9_ce0_local = 1'b1;
    end else begin
        output_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (select_ln139_read_reg_673 == 4'd9))) begin
        output_9_we0_local = 1'b1;
    end else begin
        output_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln174_1_fu_410_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 5'd1);

assign add_ln174_fu_457_p2 = (oh_fu_120 + 3'd1);

assign add_ln175_fu_503_p2 = (select_ln174_fu_469_p3 + 3'd1);

assign add_ln180_fu_543_p2 = (zext_ln175_fu_540_p1 + or_ln_fu_530_p3);

assign add_ln_fu_489_p3 = {{trunc_ln178_fu_485_p1}, {select_ln174_fu_469_p3}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign buffer_0_address0 = zext_ln180_fu_549_p1;

assign buffer_0_address1 = zext_ln178_fu_497_p1;

assign buffer_0_ce0 = buffer_0_ce0_local;

assign buffer_0_ce1 = buffer_0_ce1_local;

assign buffer_0_d0 = 32'd0;

assign buffer_0_d1 = 32'd0;

assign buffer_0_we0 = buffer_0_we0_local;

assign buffer_0_we1 = buffer_0_we1_local;

assign buffer_1_address0 = zext_ln180_fu_549_p1;

assign buffer_1_address1 = zext_ln178_fu_497_p1;

assign buffer_1_ce0 = buffer_1_ce0_local;

assign buffer_1_ce1 = buffer_1_ce1_local;

assign buffer_1_d0 = 32'd0;

assign buffer_1_d1 = 32'd0;

assign buffer_1_we0 = buffer_1_we0_local;

assign buffer_1_we1 = buffer_1_we1_local;

assign grp_fu_642_p0 = grp_fu_642_p00;

assign grp_fu_642_p00 = tmp_s_fu_519_p3;

assign grp_fu_642_p1 = grp_fu_642_p10;

assign grp_fu_642_p10 = select_ln174_reg_691;

assign grp_fu_642_p2 = 9'd19;

assign icmp_ln174_fu_404_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln175_fu_463_p2 = ((ow_fu_116 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln182_1_fu_569_p2 = (($signed(buffer_0_q0) > $signed(buffer_1_q0)) ? 1'b1 : 1'b0);

assign icmp_ln182_2_fu_583_p2 = (($signed(select_ln182_reg_727_pp0_iter3_reg) > $signed(select_ln182_1_reg_733)) ? 1'b1 : 1'b0);

assign icmp_ln182_fu_555_p2 = (($signed(buffer_0_q1) > $signed(buffer_1_q1)) ? 1'b1 : 1'b0);

assign mx_fu_587_p3 = ((icmp_ln182_2_fu_583_p2[0:0] == 1'b1) ? select_ln182_reg_727_pp0_iter3_reg : select_ln182_1_reg_733);

assign or_ln_fu_530_p3 = {{trunc_ln178_reg_702}, {3'd4}};

assign output_0_address0 = zext_ln184_2_fu_606_p1;

assign output_0_ce0 = output_0_ce0_local;

assign output_0_d0 = xor_ln25_fu_623_p2;

assign output_0_we0 = output_0_we0_local;

assign output_10_address0 = zext_ln184_2_fu_606_p1;

assign output_10_ce0 = output_10_ce0_local;

assign output_10_d0 = xor_ln25_fu_623_p2;

assign output_10_we0 = output_10_we0_local;

assign output_11_address0 = zext_ln184_2_fu_606_p1;

assign output_11_ce0 = output_11_ce0_local;

assign output_11_d0 = xor_ln25_fu_623_p2;

assign output_11_we0 = output_11_we0_local;

assign output_12_address0 = zext_ln184_2_fu_606_p1;

assign output_12_ce0 = output_12_ce0_local;

assign output_12_d0 = xor_ln25_fu_623_p2;

assign output_12_we0 = output_12_we0_local;

assign output_13_address0 = zext_ln184_2_fu_606_p1;

assign output_13_ce0 = output_13_ce0_local;

assign output_13_d0 = xor_ln25_fu_623_p2;

assign output_13_we0 = output_13_we0_local;

assign output_1_address0 = zext_ln184_2_fu_606_p1;

assign output_1_ce0 = output_1_ce0_local;

assign output_1_d0 = xor_ln25_fu_623_p2;

assign output_1_we0 = output_1_we0_local;

assign output_2_address0 = zext_ln184_2_fu_606_p1;

assign output_2_ce0 = output_2_ce0_local;

assign output_2_d0 = xor_ln25_fu_623_p2;

assign output_2_we0 = output_2_we0_local;

assign output_3_address0 = zext_ln184_2_fu_606_p1;

assign output_3_ce0 = output_3_ce0_local;

assign output_3_d0 = xor_ln25_fu_623_p2;

assign output_3_we0 = output_3_we0_local;

assign output_4_address0 = zext_ln184_2_fu_606_p1;

assign output_4_ce0 = output_4_ce0_local;

assign output_4_d0 = xor_ln25_fu_623_p2;

assign output_4_we0 = output_4_we0_local;

assign output_5_address0 = zext_ln184_2_fu_606_p1;

assign output_5_ce0 = output_5_ce0_local;

assign output_5_d0 = xor_ln25_fu_623_p2;

assign output_5_we0 = output_5_we0_local;

assign output_6_address0 = zext_ln184_2_fu_606_p1;

assign output_6_ce0 = output_6_ce0_local;

assign output_6_d0 = xor_ln25_fu_623_p2;

assign output_6_we0 = output_6_we0_local;

assign output_7_address0 = zext_ln184_2_fu_606_p1;

assign output_7_ce0 = output_7_ce0_local;

assign output_7_d0 = xor_ln25_fu_623_p2;

assign output_7_we0 = output_7_we0_local;

assign output_8_address0 = zext_ln184_2_fu_606_p1;

assign output_8_ce0 = output_8_ce0_local;

assign output_8_d0 = xor_ln25_fu_623_p2;

assign output_8_we0 = output_8_we0_local;

assign output_9_address0 = zext_ln184_2_fu_606_p1;

assign output_9_ce0 = output_9_ce0_local;

assign output_9_d0 = xor_ln25_fu_623_p2;

assign output_9_we0 = output_9_we0_local;

assign select_ln139_read_reg_673 = select_ln139;

assign select_ln174_1_fu_477_p3 = ((icmp_ln175_fu_463_p2[0:0] == 1'b1) ? add_ln174_fu_457_p2 : oh_fu_120);

assign select_ln174_fu_469_p3 = ((icmp_ln175_fu_463_p2[0:0] == 1'b1) ? 3'd0 : ow_fu_116);

assign select_ln182_1_fu_575_p3 = ((icmp_ln182_1_fu_569_p2[0:0] == 1'b1) ? buffer_0_q0 : buffer_1_q0);

assign select_ln182_fu_561_p3 = ((icmp_ln182_fu_555_p2[0:0] == 1'b1) ? buffer_0_q1 : buffer_1_q1);

assign sext_ln149_cast_fu_382_p1 = $signed(sext_ln149);

assign tmp_s_fu_519_p3 = {{select_ln174_1_reg_697}, {2'd0}};

assign trunc_ln178_fu_485_p1 = select_ln174_1_fu_477_p3[1:0];

assign val_fu_593_p2 = ($signed(mx_fu_587_p3) + $signed(sext_ln149_cast_reg_682));

assign xor_ln25_fu_623_p2 = (tmp_reg_739 ^ 1'd1);

assign zext_ln175_fu_540_p1 = select_ln174_reg_691;

assign zext_ln178_fu_497_p1 = add_ln_fu_489_p3;

assign zext_ln180_fu_549_p1 = add_ln180_fu_543_p2;

assign zext_ln184_2_fu_606_p1 = grp_fu_642_p4;

endmodule //kernel_conv2d_l3_Pipeline_L3_FH_L3_FW
