-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity kernel_kernel_Pipeline_MLPO_BITS is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    mlpo_acc : IN STD_LOGIC_VECTOR (31 downto 0);
    sext_ln486 : IN STD_LOGIC_VECTOR (31 downto 0);
    mlp_hidden_2_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    mlp_hidden_2_ce0 : OUT STD_LOGIC;
    mlp_hidden_2_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_49 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_50 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_51 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_52 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_53 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_54 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_55 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_56 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_57 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_58 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_59 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_60 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_61 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_62 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_63 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_64 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_65 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_66 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_67 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_68 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_69 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_70 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_71 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_72 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_73 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_74 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_75 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty : IN STD_LOGIC_VECTOR (4 downto 0);
    mlpo_acc_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    mlpo_acc_2_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of kernel_kernel_Pipeline_MLPO_BITS is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv11_39 : STD_LOGIC_VECTOR (10 downto 0) := "00000111001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal or_cond_fu_629_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal icmp_ln489_fu_433_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln489_reg_718 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal w_fu_591_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal w_reg_728 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_reg_733 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln489_fu_418_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal mlpo_acc_2_fu_672_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal phi_urem27_fu_146 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal select_ln487_fu_400_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_phi_urem27_load : STD_LOGIC_VECTOR (4 downto 0);
    signal phi_mul25_fu_150 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln491_fu_439_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_phi_mul25_load : STD_LOGIC_VECTOR (10 downto 0);
    signal mlpo_acc_1_fu_154 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal i_1_fu_158 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln486_fu_617_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_i : STD_LOGIC_VECTOR (4 downto 0);
    signal mlp_hidden_2_ce0_local : STD_LOGIC;
    signal icmp_ln487_fu_394_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln487_fu_388_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln487_fu_408_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln486_cast_fu_355_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln488_fu_412_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_31_fu_423_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_fu_459_p19 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln491_fu_455_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_503_p19 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_547_p19 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_459_p21 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_503_p21 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_547_p21 : STD_LOGIC_VECTOR (0 downto 0);
    signal w_fu_591_p7 : STD_LOGIC_VECTOR (0 downto 0);
    signal w_fu_591_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln486_fu_623_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_icmp_ln489_fu_611_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln492_fu_653_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln492_fu_658_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal mlpo_acc_5_fu_666_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_fu_459_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_459_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_459_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_459_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_459_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_459_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_459_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_459_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_459_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_503_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_503_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_503_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_503_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_503_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_503_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_503_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_503_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_503_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_547_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_547_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_547_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_547_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_547_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_547_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_547_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_547_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_547_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal w_fu_591_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal w_fu_591_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal w_fu_591_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component kernel_sparsemux_19_4_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (3 downto 0);
        din8_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        din3 : IN STD_LOGIC_VECTOR (0 downto 0);
        din4 : IN STD_LOGIC_VECTOR (0 downto 0);
        din5 : IN STD_LOGIC_VECTOR (0 downto 0);
        din6 : IN STD_LOGIC_VECTOR (0 downto 0);
        din7 : IN STD_LOGIC_VECTOR (0 downto 0);
        din8 : IN STD_LOGIC_VECTOR (0 downto 0);
        def : IN STD_LOGIC_VECTOR (0 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component kernel_sparsemux_7_2_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        def : IN STD_LOGIC_VECTOR (0 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_19_4_1_1_1_U660 : component kernel_sparsemux_19_4_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 1,
        CASE1 => "0001",
        din1_WIDTH => 1,
        CASE2 => "0010",
        din2_WIDTH => 1,
        CASE3 => "0011",
        din3_WIDTH => 1,
        CASE4 => "0100",
        din4_WIDTH => 1,
        CASE5 => "0101",
        din5_WIDTH => 1,
        CASE6 => "0110",
        din6_WIDTH => 1,
        CASE7 => "0111",
        din7_WIDTH => 1,
        CASE8 => "1000",
        din8_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 4,
        dout_WIDTH => 1)
    port map (
        din0 => empty_49,
        din1 => empty_50,
        din2 => empty_51,
        din3 => empty_52,
        din4 => empty_53,
        din5 => empty_54,
        din6 => empty_55,
        din7 => empty_56,
        din8 => empty_57,
        def => tmp_fu_459_p19,
        sel => trunc_ln491_fu_455_p1,
        dout => tmp_fu_459_p21);

    sparsemux_19_4_1_1_1_U661 : component kernel_sparsemux_19_4_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 1,
        CASE1 => "0001",
        din1_WIDTH => 1,
        CASE2 => "0010",
        din2_WIDTH => 1,
        CASE3 => "0011",
        din3_WIDTH => 1,
        CASE4 => "0100",
        din4_WIDTH => 1,
        CASE5 => "0101",
        din5_WIDTH => 1,
        CASE6 => "0110",
        din6_WIDTH => 1,
        CASE7 => "0111",
        din7_WIDTH => 1,
        CASE8 => "1000",
        din8_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 4,
        dout_WIDTH => 1)
    port map (
        din0 => empty_58,
        din1 => empty_59,
        din2 => empty_60,
        din3 => empty_61,
        din4 => empty_62,
        din5 => empty_63,
        din6 => empty_64,
        din7 => empty_65,
        din8 => empty_66,
        def => tmp_1_fu_503_p19,
        sel => trunc_ln491_fu_455_p1,
        dout => tmp_1_fu_503_p21);

    sparsemux_19_4_1_1_1_U662 : component kernel_sparsemux_19_4_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 1,
        CASE1 => "0001",
        din1_WIDTH => 1,
        CASE2 => "0010",
        din2_WIDTH => 1,
        CASE3 => "0011",
        din3_WIDTH => 1,
        CASE4 => "0100",
        din4_WIDTH => 1,
        CASE5 => "0101",
        din5_WIDTH => 1,
        CASE6 => "0110",
        din6_WIDTH => 1,
        CASE7 => "0111",
        din7_WIDTH => 1,
        CASE8 => "1000",
        din8_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 4,
        dout_WIDTH => 1)
    port map (
        din0 => empty_67,
        din1 => empty_68,
        din2 => empty_69,
        din3 => empty_70,
        din4 => empty_71,
        din5 => empty_72,
        din6 => empty_73,
        din7 => empty_74,
        din8 => empty_75,
        def => tmp_2_fu_547_p19,
        sel => trunc_ln491_fu_455_p1,
        dout => tmp_2_fu_547_p21);

    sparsemux_7_2_1_1_1_U663 : component kernel_sparsemux_7_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "10",
        din2_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => tmp_fu_459_p21,
        din1 => tmp_1_fu_503_p21,
        din2 => tmp_2_fu_547_p21,
        def => w_fu_591_p7,
        sel => w_fu_591_p8,
        dout => w_fu_591_p9);

    flow_control_loop_pipe_sequential_init_U : component kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if (((ap_loop_exit_ready = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                end if;
            end if; 
        end if;
    end process;

    i_1_fu_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then 
                    i_1_fu_158 <= add_ln486_fu_617_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_1_fu_158 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    mlpo_acc_1_fu_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    mlpo_acc_1_fu_154 <= mlpo_acc;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    mlpo_acc_1_fu_154 <= mlpo_acc_2_fu_672_p3;
                end if;
            end if; 
        end if;
    end process;

    phi_mul25_fu_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then 
                    phi_mul25_fu_150 <= add_ln491_fu_439_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    phi_mul25_fu_150 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;

    phi_urem27_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then 
                    phi_urem27_fu_146 <= select_ln487_fu_400_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    phi_urem27_fu_146 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln489_reg_718 <= icmp_ln489_fu_433_p2;
                or_cond_reg_733 <= or_cond_fu_629_p2;
                w_reg_728 <= w_fu_591_p9;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln486_fu_617_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i) + unsigned(ap_const_lv5_1));
    add_ln487_fu_388_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_urem27_load) + unsigned(ap_const_lv5_1));
    add_ln488_fu_412_p2 <= std_logic_vector(unsigned(zext_ln487_fu_408_p1) + unsigned(sext_ln486_cast_fu_355_p1));
    add_ln491_fu_439_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_mul25_load) + unsigned(ap_const_lv11_39));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, or_cond_fu_629_p2)
    begin
        if (((or_cond_fu_629_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter1_reg, ap_done_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_1_fu_158)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_i <= i_1_fu_158;
        end if; 
    end process;


    ap_sig_allocacmp_phi_mul25_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, phi_mul25_fu_150)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_phi_mul25_load <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_phi_mul25_load <= phi_mul25_fu_150;
        end if; 
    end process;


    ap_sig_allocacmp_phi_urem27_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, phi_urem27_fu_146, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_phi_urem27_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_phi_urem27_load <= phi_urem27_fu_146;
        end if; 
    end process;

    icmp_ln486_fu_623_p2 <= "1" when (unsigned(add_ln486_fu_617_p2) < unsigned(empty)) else "0";
    icmp_ln487_fu_394_p2 <= "1" when (ap_sig_allocacmp_phi_urem27_load = ap_const_lv5_8) else "0";
    icmp_ln489_fu_433_p2 <= "1" when (signed(tmp_31_fu_423_p4) > signed(ap_const_lv24_0)) else "0";
    mlp_hidden_2_address0 <= zext_ln489_fu_418_p1(9 - 1 downto 0);
    mlp_hidden_2_ce0 <= mlp_hidden_2_ce0_local;

    mlp_hidden_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            mlp_hidden_2_ce0_local <= ap_const_logic_1;
        else 
            mlp_hidden_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    mlpo_acc_2_fu_672_p3 <= 
        mlpo_acc_1_fu_154 when (icmp_ln489_reg_718(0) = '1') else 
        mlpo_acc_5_fu_666_p2;
    mlpo_acc_2_out <= 
        mlpo_acc_1_fu_154 when (icmp_ln489_reg_718(0) = '1') else 
        mlpo_acc_5_fu_666_p2;

    mlpo_acc_2_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, or_cond_reg_733, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (or_cond_reg_733 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            mlpo_acc_2_out_ap_vld <= ap_const_logic_1;
        else 
            mlpo_acc_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mlpo_acc_5_fu_666_p2 <= std_logic_vector(unsigned(select_ln492_fu_658_p3) + unsigned(mlpo_acc_1_fu_154));
    not_icmp_ln489_fu_611_p2 <= (icmp_ln489_fu_433_p2 xor ap_const_lv1_1);
    or_cond_fu_629_p2 <= (not_icmp_ln489_fu_611_p2 and icmp_ln486_fu_623_p2);
    select_ln487_fu_400_p3 <= 
        ap_const_lv5_0 when (icmp_ln487_fu_394_p2(0) = '1') else 
        add_ln487_fu_388_p2;
    select_ln492_fu_658_p3 <= 
        ap_const_lv32_FFFFFFFF when (xor_ln492_fu_653_p2(0) = '1') else 
        ap_const_lv32_1;
        sext_ln486_cast_fu_355_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln486),33));

    tmp_1_fu_503_p19 <= "X";
    tmp_2_fu_547_p19 <= "X";
    tmp_31_fu_423_p4 <= add_ln488_fu_412_p2(32 downto 9);
    tmp_fu_459_p19 <= "X";
    trunc_ln491_fu_455_p1 <= ap_sig_allocacmp_phi_urem27_load(4 - 1 downto 0);
    w_fu_591_p7 <= "X";
    w_fu_591_p8 <= ap_sig_allocacmp_phi_mul25_load(10 downto 9);
    xor_ln492_fu_653_p2 <= (w_reg_728 xor mlp_hidden_2_q0);
    zext_ln487_fu_408_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i),33));
    zext_ln489_fu_418_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln488_fu_412_p2),64));
end behav;
