# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/oldak/Binary-CNN-Accelerator/vivado_project/vivado_project.srcs/sources_1/bd/cnn_accel/ip/cnn_accel_rst_ps7_0_76M_0/cnn_accel_rst_ps7_0_76M_0.xci
# IP: The module: 'cnn_accel_rst_ps7_0_76M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/oldak/Binary-CNN-Accelerator/vivado_project/vivado_project.gen/sources_1/bd/cnn_accel/ip/cnn_accel_rst_ps7_0_76M_0/cnn_accel_rst_ps7_0_76M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnn_accel_rst_ps7_0_76M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/oldak/Binary-CNN-Accelerator/vivado_project/vivado_project.gen/sources_1/bd/cnn_accel/ip/cnn_accel_rst_ps7_0_76M_0/cnn_accel_rst_ps7_0_76M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnn_accel_rst_ps7_0_76M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/oldak/Binary-CNN-Accelerator/vivado_project/vivado_project.srcs/sources_1/bd/cnn_accel/ip/cnn_accel_rst_ps7_0_76M_0/cnn_accel_rst_ps7_0_76M_0.xci
# IP: The module: 'cnn_accel_rst_ps7_0_76M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/oldak/Binary-CNN-Accelerator/vivado_project/vivado_project.gen/sources_1/bd/cnn_accel/ip/cnn_accel_rst_ps7_0_76M_0/cnn_accel_rst_ps7_0_76M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnn_accel_rst_ps7_0_76M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/oldak/Binary-CNN-Accelerator/vivado_project/vivado_project.gen/sources_1/bd/cnn_accel/ip/cnn_accel_rst_ps7_0_76M_0/cnn_accel_rst_ps7_0_76M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnn_accel_rst_ps7_0_76M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
