-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity kernel_softmax_Pipeline_SM_NORM is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    es_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    probs_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    probs_ce0 : OUT STD_LOGIC;
    probs_we0 : OUT STD_LOGIC;
    probs_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ev_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    ev_ce0 : OUT STD_LOGIC;
    ev_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of kernel_softmax_Pipeline_SM_NORM is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter21 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter22 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter23 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter24 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter25 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter26 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter27 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter28 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter29 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter30 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter31 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter32 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter33 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter34 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter35 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter36 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln333_fu_100_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln335_fu_86_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln335_reg_156 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter27_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter28_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter29_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter30_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter31_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter32_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter33_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter34_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_160_pp0_iter35_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln333_fu_112_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter8_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter9_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter10_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter11_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter12_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter13_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter14_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter15_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter16_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter17_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter18_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter19_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter20_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter21_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter22_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter23_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter24_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter25_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter26_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter27_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter28_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter29_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter30_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter31_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter32_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter33_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter34_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln333_reg_164_pp0_iter35_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_mux_cond33_phi_fu_78_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln335_fu_139_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter36_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter1_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter2_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter3_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter4_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter5_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter6_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter7_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter8_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter9_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter10_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter11_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter12_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter13_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter14_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter15_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter16_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter17_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter18_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter19_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter20_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter21_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter22_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter23_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter24_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter25_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter26_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter27_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter28_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter29_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter30_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter31_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter32_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter33_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter34_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter35_cond33_reg_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_fu_38 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln333_fu_106_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ev_ce0_local : STD_LOGIC;
    signal probs_we0_local : STD_LOGIC;
    signal probs_ce0_local : STD_LOGIC;
    signal shl_ln335_fu_122_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_134_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_134_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter18_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter19_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter20_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter21_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter22_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter23_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter24_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter25_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter26_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter27_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter28_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter29_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter30_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter31_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter32_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter33_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter34_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter35_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_376 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component kernel_sdiv_32ns_32ns_16_36_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sdiv_32ns_32ns_16_36_1_U696 : component kernel_sdiv_32ns_32ns_16_36_1
    generic map (
        ID => 1,
        NUM_STAGE => 36,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_134_p0,
        din1 => es_1,
        ce => ap_const_logic_1,
        dout => grp_fu_134_p2);

    flow_control_loop_pipe_sequential_init_U : component kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter35_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter21_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter21 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter22_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter22 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter23_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter23 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter24_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter24 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter25_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter25 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter26_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter26 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter27_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter27 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter28_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter28 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter29_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter29 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter30_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter30 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter31_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter31 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter32_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter32 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter33_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter33 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter34_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter34 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter35_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter35 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter36_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter36 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_cond33_reg_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_376)) then
                if (((icmp_ln335_fu_86_p2 = ap_const_lv1_0) and (icmp_ln333_fu_100_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_cond33_reg_74 <= ap_const_lv16_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_cond33_reg_74 <= ap_phi_reg_pp0_iter0_cond33_reg_74;
                end if;
            end if; 
        end if;
    end process;

    i_fu_38_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln333_fu_100_p2 = ap_const_lv1_0))) then 
                    i_fu_38 <= add_ln333_fu_106_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_38 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
                ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
                ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
                ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
                ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
                ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
                ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
                ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
                ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
                ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
                ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
                ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
                ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
                ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
                ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
                ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
                ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
                ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
                ap_loop_exit_ready_pp0_iter35_reg <= ap_loop_exit_ready_pp0_iter34_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                icmp_ln333_reg_160_pp0_iter10_reg <= icmp_ln333_reg_160_pp0_iter9_reg;
                icmp_ln333_reg_160_pp0_iter11_reg <= icmp_ln333_reg_160_pp0_iter10_reg;
                icmp_ln333_reg_160_pp0_iter12_reg <= icmp_ln333_reg_160_pp0_iter11_reg;
                icmp_ln333_reg_160_pp0_iter13_reg <= icmp_ln333_reg_160_pp0_iter12_reg;
                icmp_ln333_reg_160_pp0_iter14_reg <= icmp_ln333_reg_160_pp0_iter13_reg;
                icmp_ln333_reg_160_pp0_iter15_reg <= icmp_ln333_reg_160_pp0_iter14_reg;
                icmp_ln333_reg_160_pp0_iter16_reg <= icmp_ln333_reg_160_pp0_iter15_reg;
                icmp_ln333_reg_160_pp0_iter17_reg <= icmp_ln333_reg_160_pp0_iter16_reg;
                icmp_ln333_reg_160_pp0_iter18_reg <= icmp_ln333_reg_160_pp0_iter17_reg;
                icmp_ln333_reg_160_pp0_iter19_reg <= icmp_ln333_reg_160_pp0_iter18_reg;
                icmp_ln333_reg_160_pp0_iter20_reg <= icmp_ln333_reg_160_pp0_iter19_reg;
                icmp_ln333_reg_160_pp0_iter21_reg <= icmp_ln333_reg_160_pp0_iter20_reg;
                icmp_ln333_reg_160_pp0_iter22_reg <= icmp_ln333_reg_160_pp0_iter21_reg;
                icmp_ln333_reg_160_pp0_iter23_reg <= icmp_ln333_reg_160_pp0_iter22_reg;
                icmp_ln333_reg_160_pp0_iter24_reg <= icmp_ln333_reg_160_pp0_iter23_reg;
                icmp_ln333_reg_160_pp0_iter25_reg <= icmp_ln333_reg_160_pp0_iter24_reg;
                icmp_ln333_reg_160_pp0_iter26_reg <= icmp_ln333_reg_160_pp0_iter25_reg;
                icmp_ln333_reg_160_pp0_iter27_reg <= icmp_ln333_reg_160_pp0_iter26_reg;
                icmp_ln333_reg_160_pp0_iter28_reg <= icmp_ln333_reg_160_pp0_iter27_reg;
                icmp_ln333_reg_160_pp0_iter29_reg <= icmp_ln333_reg_160_pp0_iter28_reg;
                icmp_ln333_reg_160_pp0_iter2_reg <= icmp_ln333_reg_160_pp0_iter1_reg;
                icmp_ln333_reg_160_pp0_iter30_reg <= icmp_ln333_reg_160_pp0_iter29_reg;
                icmp_ln333_reg_160_pp0_iter31_reg <= icmp_ln333_reg_160_pp0_iter30_reg;
                icmp_ln333_reg_160_pp0_iter32_reg <= icmp_ln333_reg_160_pp0_iter31_reg;
                icmp_ln333_reg_160_pp0_iter33_reg <= icmp_ln333_reg_160_pp0_iter32_reg;
                icmp_ln333_reg_160_pp0_iter34_reg <= icmp_ln333_reg_160_pp0_iter33_reg;
                icmp_ln333_reg_160_pp0_iter35_reg <= icmp_ln333_reg_160_pp0_iter34_reg;
                icmp_ln333_reg_160_pp0_iter3_reg <= icmp_ln333_reg_160_pp0_iter2_reg;
                icmp_ln333_reg_160_pp0_iter4_reg <= icmp_ln333_reg_160_pp0_iter3_reg;
                icmp_ln333_reg_160_pp0_iter5_reg <= icmp_ln333_reg_160_pp0_iter4_reg;
                icmp_ln333_reg_160_pp0_iter6_reg <= icmp_ln333_reg_160_pp0_iter5_reg;
                icmp_ln333_reg_160_pp0_iter7_reg <= icmp_ln333_reg_160_pp0_iter6_reg;
                icmp_ln333_reg_160_pp0_iter8_reg <= icmp_ln333_reg_160_pp0_iter7_reg;
                icmp_ln333_reg_160_pp0_iter9_reg <= icmp_ln333_reg_160_pp0_iter8_reg;
                    zext_ln333_reg_164_pp0_iter10_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter9_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter11_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter10_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter12_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter11_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter13_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter12_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter14_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter13_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter15_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter14_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter16_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter15_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter17_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter16_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter18_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter17_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter19_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter18_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter20_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter19_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter21_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter20_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter22_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter21_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter23_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter22_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter24_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter23_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter25_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter24_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter26_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter25_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter27_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter26_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter28_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter27_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter29_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter28_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter2_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter1_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter30_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter29_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter31_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter30_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter32_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter31_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter33_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter32_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter34_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter33_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter35_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter34_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter3_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter2_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter4_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter3_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter5_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter4_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter6_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter5_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter7_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter6_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter8_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter7_reg(3 downto 0);
                    zext_ln333_reg_164_pp0_iter9_reg(3 downto 0) <= zext_ln333_reg_164_pp0_iter8_reg(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln333_reg_160 <= icmp_ln333_fu_100_p2;
                icmp_ln333_reg_160_pp0_iter1_reg <= icmp_ln333_reg_160;
                icmp_ln335_reg_156 <= icmp_ln335_fu_86_p2;
                    zext_ln333_reg_164(3 downto 0) <= zext_ln333_fu_112_p1(3 downto 0);
                    zext_ln333_reg_164_pp0_iter1_reg(3 downto 0) <= zext_ln333_reg_164(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter10_cond33_reg_74 <= ap_phi_reg_pp0_iter9_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter11_cond33_reg_74 <= ap_phi_reg_pp0_iter10_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter12_cond33_reg_74 <= ap_phi_reg_pp0_iter11_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter13_cond33_reg_74 <= ap_phi_reg_pp0_iter12_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter14_cond33_reg_74 <= ap_phi_reg_pp0_iter13_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter15_cond33_reg_74 <= ap_phi_reg_pp0_iter14_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter16_cond33_reg_74 <= ap_phi_reg_pp0_iter15_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter17_cond33_reg_74 <= ap_phi_reg_pp0_iter16_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter18_cond33_reg_74 <= ap_phi_reg_pp0_iter17_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter18 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter19_cond33_reg_74 <= ap_phi_reg_pp0_iter18_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter19 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter20_cond33_reg_74 <= ap_phi_reg_pp0_iter19_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter20 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter21_cond33_reg_74 <= ap_phi_reg_pp0_iter20_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter21 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter22_cond33_reg_74 <= ap_phi_reg_pp0_iter21_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter22 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter23_cond33_reg_74 <= ap_phi_reg_pp0_iter22_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter23 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter24_cond33_reg_74 <= ap_phi_reg_pp0_iter23_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter24 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter25_cond33_reg_74 <= ap_phi_reg_pp0_iter24_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter25 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter26_cond33_reg_74 <= ap_phi_reg_pp0_iter25_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter26 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter27_cond33_reg_74 <= ap_phi_reg_pp0_iter26_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter28_cond33_reg_74 <= ap_phi_reg_pp0_iter27_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter28 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter29_cond33_reg_74 <= ap_phi_reg_pp0_iter28_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter2_cond33_reg_74 <= ap_phi_reg_pp0_iter1_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter29 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter30_cond33_reg_74 <= ap_phi_reg_pp0_iter29_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter30 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter31_cond33_reg_74 <= ap_phi_reg_pp0_iter30_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter31 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter32_cond33_reg_74 <= ap_phi_reg_pp0_iter31_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter32 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter33_cond33_reg_74 <= ap_phi_reg_pp0_iter32_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter33 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter34_cond33_reg_74 <= ap_phi_reg_pp0_iter33_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter34 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter35_cond33_reg_74 <= ap_phi_reg_pp0_iter34_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter35 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter36_cond33_reg_74 <= ap_phi_reg_pp0_iter35_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter3_cond33_reg_74 <= ap_phi_reg_pp0_iter2_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter4_cond33_reg_74 <= ap_phi_reg_pp0_iter3_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter5_cond33_reg_74 <= ap_phi_reg_pp0_iter4_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter6_cond33_reg_74 <= ap_phi_reg_pp0_iter5_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter7_cond33_reg_74 <= ap_phi_reg_pp0_iter6_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter8_cond33_reg_74 <= ap_phi_reg_pp0_iter7_cond33_reg_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter9_cond33_reg_74 <= ap_phi_reg_pp0_iter8_cond33_reg_74;
            end if;
        end if;
    end process;
    zext_ln333_reg_164(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter1_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter2_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter3_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter4_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter5_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter6_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter7_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter8_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter9_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter10_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter11_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter12_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter13_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter14_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter15_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter16_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter17_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter18_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter19_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter20_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter21_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter22_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter23_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter24_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter25_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter26_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter27_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter28_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter29_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter30_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter31_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter32_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter33_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter34_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln333_reg_164_pp0_iter35_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln333_fu_106_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv4_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_376_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_376 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln333_fu_100_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln333_fu_100_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter35_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter35_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_idle_pp0 = ap_const_logic_1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23, ap_enable_reg_pp0_iter24, ap_enable_reg_pp0_iter25, ap_enable_reg_pp0_iter26, ap_enable_reg_pp0_iter27, ap_enable_reg_pp0_iter28, ap_enable_reg_pp0_iter29, ap_enable_reg_pp0_iter30, ap_enable_reg_pp0_iter31, ap_enable_reg_pp0_iter32, ap_enable_reg_pp0_iter33, ap_enable_reg_pp0_iter34, ap_enable_reg_pp0_iter35, ap_enable_reg_pp0_iter36)
    begin
        if (((ap_enable_reg_pp0_iter26 = ap_const_logic_0) and (ap_enable_reg_pp0_iter25 = ap_const_logic_0) and (ap_enable_reg_pp0_iter24 = ap_const_logic_0) and (ap_enable_reg_pp0_iter23 = ap_const_logic_0) and (ap_enable_reg_pp0_iter22 = ap_const_logic_0) and (ap_enable_reg_pp0_iter21 = ap_const_logic_0) and (ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = 
    ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter36 = ap_const_logic_0) and (ap_enable_reg_pp0_iter35 = ap_const_logic_0) and (ap_enable_reg_pp0_iter34 = ap_const_logic_0) and (ap_enable_reg_pp0_iter33 = ap_const_logic_0) and (ap_enable_reg_pp0_iter32 = ap_const_logic_0) and (ap_enable_reg_pp0_iter31 = ap_const_logic_0) and (ap_enable_reg_pp0_iter30 = ap_const_logic_0) and (ap_enable_reg_pp0_iter29 = ap_const_logic_0) and (ap_enable_reg_pp0_iter28 = ap_const_logic_0) and (ap_enable_reg_pp0_iter27 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_cond33_phi_fu_78_p4_assign_proc : process(icmp_ln335_reg_156, icmp_ln333_reg_160_pp0_iter35_reg, trunc_ln335_fu_139_p1, ap_phi_reg_pp0_iter36_cond33_reg_74)
    begin
        if (((icmp_ln333_reg_160_pp0_iter35_reg = ap_const_lv1_0) and (icmp_ln335_reg_156 = ap_const_lv1_1))) then 
            ap_phi_mux_cond33_phi_fu_78_p4 <= trunc_ln335_fu_139_p1;
        else 
            ap_phi_mux_cond33_phi_fu_78_p4 <= ap_phi_reg_pp0_iter36_cond33_reg_74;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_cond33_reg_74 <= "XXXXXXXXXXXXXXXX";
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_38, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_38;
        end if; 
    end process;

    ev_address0 <= zext_ln333_fu_112_p1(4 - 1 downto 0);
    ev_ce0 <= ev_ce0_local;

    ev_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            ev_ce0_local <= ap_const_logic_1;
        else 
            ev_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_134_p0 <= std_logic_vector(unsigned(shl_ln335_fu_122_p2) - unsigned(ev_q0));
    icmp_ln333_fu_100_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv4_A) else "0";
    icmp_ln335_fu_86_p2 <= "1" when (signed(es_1) > signed(ap_const_lv32_0)) else "0";
    probs_address0 <= zext_ln333_reg_164_pp0_iter35_reg(4 - 1 downto 0);
    probs_ce0 <= probs_ce0_local;

    probs_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter36, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter36 = ap_const_logic_1))) then 
            probs_ce0_local <= ap_const_logic_1;
        else 
            probs_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    probs_d0 <= ap_phi_mux_cond33_phi_fu_78_p4;
    probs_we0 <= probs_we0_local;

    probs_we0_local_assign_proc : process(ap_enable_reg_pp0_iter36, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter36 = ap_const_logic_1))) then 
            probs_we0_local <= ap_const_logic_1;
        else 
            probs_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    shl_ln335_fu_122_p2 <= std_logic_vector(shift_left(unsigned(ev_q0),to_integer(unsigned('0' & ap_const_lv32_10(31-1 downto 0)))));
    trunc_ln335_fu_139_p1 <= grp_fu_134_p2(16 - 1 downto 0);
    zext_ln333_fu_112_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_1),64));
end behav;
