// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module kernel_conv2d_l2_Pipeline_L2_FH_L2_FW (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln140,
        output_0_address0,
        output_0_ce0,
        output_0_we0,
        output_0_d0,
        output_1_address0,
        output_1_ce0,
        output_1_we0,
        output_1_d0,
        output_2_address0,
        output_2_ce0,
        output_2_we0,
        output_2_d0,
        output_3_address0,
        output_3_ce0,
        output_3_we0,
        output_3_d0,
        output_4_address0,
        output_4_ce0,
        output_4_we0,
        output_4_d0,
        output_5_address0,
        output_5_ce0,
        output_5_we0,
        output_5_d0,
        output_6_address0,
        output_6_ce0,
        output_6_we0,
        output_6_d0,
        output_7_address0,
        output_7_ce0,
        output_7_we0,
        output_7_d0,
        output_8_address0,
        output_8_ce0,
        output_8_we0,
        output_8_d0,
        output_9_address0,
        output_9_ce0,
        output_9_we0,
        output_9_d0,
        output_10_address0,
        output_10_ce0,
        output_10_we0,
        output_10_d0,
        output_11_address0,
        output_11_ce0,
        output_11_we0,
        output_11_d0,
        output_12_address0,
        output_12_ce0,
        output_12_we0,
        output_12_d0,
        output_13_address0,
        output_13_ce0,
        output_13_we0,
        output_13_d0,
        buffer_1_address0,
        buffer_1_ce0,
        buffer_1_we0,
        buffer_1_d0,
        buffer_1_q0,
        buffer_1_address1,
        buffer_1_ce1,
        buffer_1_we1,
        buffer_1_d1,
        buffer_1_q1,
        buffer_0_address0,
        buffer_0_ce0,
        buffer_0_we0,
        buffer_0_d0,
        buffer_0_q0,
        buffer_0_address1,
        buffer_0_ce1,
        buffer_0_we1,
        buffer_0_d1,
        buffer_0_q1,
        sext_ln150,
        select_ln140
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [9:0] zext_ln140;
output  [9:0] output_0_address0;
output   output_0_ce0;
output   output_0_we0;
output  [0:0] output_0_d0;
output  [9:0] output_1_address0;
output   output_1_ce0;
output   output_1_we0;
output  [0:0] output_1_d0;
output  [9:0] output_2_address0;
output   output_2_ce0;
output   output_2_we0;
output  [0:0] output_2_d0;
output  [9:0] output_3_address0;
output   output_3_ce0;
output   output_3_we0;
output  [0:0] output_3_d0;
output  [9:0] output_4_address0;
output   output_4_ce0;
output   output_4_we0;
output  [0:0] output_4_d0;
output  [9:0] output_5_address0;
output   output_5_ce0;
output   output_5_we0;
output  [0:0] output_5_d0;
output  [9:0] output_6_address0;
output   output_6_ce0;
output   output_6_we0;
output  [0:0] output_6_d0;
output  [9:0] output_7_address0;
output   output_7_ce0;
output   output_7_we0;
output  [0:0] output_7_d0;
output  [9:0] output_8_address0;
output   output_8_ce0;
output   output_8_we0;
output  [0:0] output_8_d0;
output  [9:0] output_9_address0;
output   output_9_ce0;
output   output_9_we0;
output  [0:0] output_9_d0;
output  [9:0] output_10_address0;
output   output_10_ce0;
output   output_10_we0;
output  [0:0] output_10_d0;
output  [9:0] output_11_address0;
output   output_11_ce0;
output   output_11_we0;
output  [0:0] output_11_d0;
output  [9:0] output_12_address0;
output   output_12_ce0;
output   output_12_we0;
output  [0:0] output_12_d0;
output  [9:0] output_13_address0;
output   output_13_ce0;
output   output_13_we0;
output  [0:0] output_13_d0;
output  [8:0] buffer_1_address0;
output   buffer_1_ce0;
output   buffer_1_we0;
output  [31:0] buffer_1_d0;
input  [31:0] buffer_1_q0;
output  [8:0] buffer_1_address1;
output   buffer_1_ce1;
output   buffer_1_we1;
output  [31:0] buffer_1_d1;
input  [31:0] buffer_1_q1;
output  [8:0] buffer_0_address0;
output   buffer_0_ce0;
output   buffer_0_we0;
output  [31:0] buffer_0_d0;
input  [31:0] buffer_0_q0;
output  [8:0] buffer_0_address1;
output   buffer_0_ce1;
output   buffer_0_we1;
output  [31:0] buffer_0_d1;
input  [31:0] buffer_0_q1;
input  [15:0] sext_ln150;
input  [3:0] select_ln140;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln175_fu_402_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [3:0] select_ln140_read_reg_705;
wire    ap_block_pp0_stage0_11001;
wire  signed [31:0] sext_ln150_cast_fu_380_p1;
reg  signed [31:0] sext_ln150_cast_reg_714;
wire   [3:0] select_ln175_fu_432_p3;
reg   [3:0] select_ln175_reg_723;
wire   [3:0] select_ln175_1_fu_440_p3;
reg   [3:0] select_ln175_1_reg_728;
wire   [9:0] add_ln185_1_fu_591_p2;
reg   [9:0] add_ln185_1_reg_753;
wire   [31:0] select_ln183_fu_602_p3;
reg   [31:0] select_ln183_reg_758;
wire   [31:0] select_ln183_1_fu_616_p3;
reg   [31:0] select_ln183_1_reg_764;
wire   [63:0] zext_ln179_fu_472_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln181_fu_484_p1;
wire   [63:0] zext_ln185_2_fu_624_p1;
reg   [3:0] ow_fu_114;
wire   [3:0] add_ln176_fu_520_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_ow_load;
reg   [3:0] oh_fu_118;
reg   [3:0] ap_sig_allocacmp_oh_load;
reg   [6:0] indvar_flatten6_fu_122;
wire   [6:0] add_ln175_1_fu_408_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten6_load;
reg    buffer_0_ce1_local;
reg    buffer_0_ce0_local;
reg    buffer_0_we1_local;
reg    buffer_0_we0_local;
reg    buffer_1_ce1_local;
reg    buffer_1_ce0_local;
reg    buffer_1_we1_local;
reg    buffer_1_we0_local;
reg    output_12_we0_local;
wire   [0:0] xor_ln61_fu_664_p2;
reg    output_12_ce0_local;
reg    output_11_we0_local;
reg    output_11_ce0_local;
reg    output_10_we0_local;
reg    output_10_ce0_local;
reg    output_9_we0_local;
reg    output_9_ce0_local;
reg    output_8_we0_local;
reg    output_8_ce0_local;
reg    output_7_we0_local;
reg    output_7_ce0_local;
reg    output_6_we0_local;
reg    output_6_ce0_local;
reg    output_5_we0_local;
reg    output_5_ce0_local;
reg    output_4_we0_local;
reg    output_4_ce0_local;
reg    output_3_we0_local;
reg    output_3_ce0_local;
reg    output_2_we0_local;
reg    output_2_ce0_local;
reg    output_1_we0_local;
reg    output_1_ce0_local;
reg    output_0_we0_local;
reg    output_0_ce0_local;
reg    output_13_we0_local;
reg    output_13_ce0_local;
wire   [0:0] icmp_ln176_fu_426_p2;
wire   [3:0] add_ln175_fu_420_p2;
wire   [2:0] trunc_ln179_fu_448_p1;
wire   [6:0] add_ln_fu_464_p3;
wire   [6:0] zext_ln176_fu_460_p1;
wire   [6:0] or_ln_fu_452_p3;
wire   [6:0] add_ln181_fu_478_p2;
wire   [6:0] tmp_s_fu_541_p3;
wire   [7:0] zext_ln179_1_fu_548_p1;
wire   [7:0] zext_ln185_fu_552_p1;
wire   [7:0] add_ln185_fu_555_p2;
wire   [6:0] trunc_ln185_fu_561_p1;
wire   [8:0] tmp_fu_573_p3;
wire   [9:0] p_shl_fu_565_p3;
wire   [9:0] zext_ln185_1_fu_581_p1;
wire   [9:0] add_ln185_2_fu_585_p2;
wire   [0:0] icmp_ln183_fu_596_p2;
wire   [0:0] icmp_ln183_1_fu_610_p2;
wire   [0:0] icmp_ln183_2_fu_641_p2;
wire   [31:0] mx_fu_645_p3;
wire   [31:0] val_fu_651_p2;
wire   [0:0] tmp_136_fu_656_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ow_fu_114 = 4'd0;
#0 oh_fu_118 = 4'd0;
#0 indvar_flatten6_fu_122 = 7'd0;
#0 ap_done_reg = 1'b0;
end

kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln175_fu_402_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten6_fu_122 <= add_ln175_1_fu_408_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_122 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln175_fu_402_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            oh_fu_118 <= select_ln175_1_fu_440_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oh_fu_118 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln175_fu_402_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            ow_fu_114 <= add_ln176_fu_520_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ow_fu_114 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln185_1_reg_753 <= add_ln185_1_fu_591_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        select_ln175_1_reg_728 <= select_ln175_1_fu_440_p3;
        select_ln175_reg_723 <= select_ln175_fu_432_p3;
        select_ln183_1_reg_764 <= select_ln183_1_fu_616_p3;
        select_ln183_reg_758 <= select_ln183_fu_602_p3;
        sext_ln150_cast_reg_714 <= sext_ln150_cast_fu_380_p1;
    end
end

always @ (*) begin
    if (((icmp_ln175_fu_402_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_122;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_oh_load = 4'd0;
    end else begin
        ap_sig_allocacmp_oh_load = oh_fu_118;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_ow_load = 4'd0;
    end else begin
        ap_sig_allocacmp_ow_load = ow_fu_114;
    end
end

always @ (*) begin
    if (((icmp_ln175_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_0_ce0_local = 1'b1;
    end else begin
        buffer_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln175_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_0_ce1_local = 1'b1;
    end else begin
        buffer_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln175_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_0_we0_local = 1'b1;
    end else begin
        buffer_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln175_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_0_we1_local = 1'b1;
    end else begin
        buffer_0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln175_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_1_ce0_local = 1'b1;
    end else begin
        buffer_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln175_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_1_ce1_local = 1'b1;
    end else begin
        buffer_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln175_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_1_we0_local = 1'b1;
    end else begin
        buffer_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln175_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_1_we1_local = 1'b1;
    end else begin
        buffer_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output_0_ce0_local = 1'b1;
    end else begin
        output_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln140_read_reg_705 == 4'd0))) begin
        output_0_we0_local = 1'b1;
    end else begin
        output_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output_10_ce0_local = 1'b1;
    end else begin
        output_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln140_read_reg_705 == 4'd10))) begin
        output_10_we0_local = 1'b1;
    end else begin
        output_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output_11_ce0_local = 1'b1;
    end else begin
        output_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln140_read_reg_705 == 4'd11))) begin
        output_11_we0_local = 1'b1;
    end else begin
        output_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output_12_ce0_local = 1'b1;
    end else begin
        output_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln140_read_reg_705 == 4'd12))) begin
        output_12_we0_local = 1'b1;
    end else begin
        output_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output_13_ce0_local = 1'b1;
    end else begin
        output_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & ((select_ln140_read_reg_705 == 4'd13) | ((select_ln140_read_reg_705 == 4'd14) | (select_ln140_read_reg_705 == 4'd15))))) begin
        output_13_we0_local = 1'b1;
    end else begin
        output_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output_1_ce0_local = 1'b1;
    end else begin
        output_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln140_read_reg_705 == 4'd1))) begin
        output_1_we0_local = 1'b1;
    end else begin
        output_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output_2_ce0_local = 1'b1;
    end else begin
        output_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln140_read_reg_705 == 4'd2))) begin
        output_2_we0_local = 1'b1;
    end else begin
        output_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output_3_ce0_local = 1'b1;
    end else begin
        output_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln140_read_reg_705 == 4'd3))) begin
        output_3_we0_local = 1'b1;
    end else begin
        output_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output_4_ce0_local = 1'b1;
    end else begin
        output_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln140_read_reg_705 == 4'd4))) begin
        output_4_we0_local = 1'b1;
    end else begin
        output_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output_5_ce0_local = 1'b1;
    end else begin
        output_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln140_read_reg_705 == 4'd5))) begin
        output_5_we0_local = 1'b1;
    end else begin
        output_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output_6_ce0_local = 1'b1;
    end else begin
        output_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln140_read_reg_705 == 4'd6))) begin
        output_6_we0_local = 1'b1;
    end else begin
        output_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output_7_ce0_local = 1'b1;
    end else begin
        output_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln140_read_reg_705 == 4'd7))) begin
        output_7_we0_local = 1'b1;
    end else begin
        output_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output_8_ce0_local = 1'b1;
    end else begin
        output_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln140_read_reg_705 == 4'd8))) begin
        output_8_we0_local = 1'b1;
    end else begin
        output_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output_9_ce0_local = 1'b1;
    end else begin
        output_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln140_read_reg_705 == 4'd9))) begin
        output_9_we0_local = 1'b1;
    end else begin
        output_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln175_1_fu_408_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 7'd1);

assign add_ln175_fu_420_p2 = (ap_sig_allocacmp_oh_load + 4'd1);

assign add_ln176_fu_520_p2 = (select_ln175_fu_432_p3 + 4'd1);

assign add_ln181_fu_478_p2 = (zext_ln176_fu_460_p1 + or_ln_fu_452_p3);

assign add_ln185_1_fu_591_p2 = (add_ln185_2_fu_585_p2 + zext_ln140);

assign add_ln185_2_fu_585_p2 = (p_shl_fu_565_p3 + zext_ln185_1_fu_581_p1);

assign add_ln185_fu_555_p2 = (zext_ln179_1_fu_548_p1 + zext_ln185_fu_552_p1);

assign add_ln_fu_464_p3 = {{trunc_ln179_fu_448_p1}, {select_ln175_fu_432_p3}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign buffer_0_address0 = zext_ln181_fu_484_p1;

assign buffer_0_address1 = zext_ln179_fu_472_p1;

assign buffer_0_ce0 = buffer_0_ce0_local;

assign buffer_0_ce1 = buffer_0_ce1_local;

assign buffer_0_d0 = 32'd0;

assign buffer_0_d1 = 32'd0;

assign buffer_0_we0 = buffer_0_we0_local;

assign buffer_0_we1 = buffer_0_we1_local;

assign buffer_1_address0 = zext_ln181_fu_484_p1;

assign buffer_1_address1 = zext_ln179_fu_472_p1;

assign buffer_1_ce0 = buffer_1_ce0_local;

assign buffer_1_ce1 = buffer_1_ce1_local;

assign buffer_1_d0 = 32'd0;

assign buffer_1_d1 = 32'd0;

assign buffer_1_we0 = buffer_1_we0_local;

assign buffer_1_we1 = buffer_1_we1_local;

assign icmp_ln175_fu_402_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln176_fu_426_p2 = ((ap_sig_allocacmp_ow_load == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln183_1_fu_610_p2 = (($signed(buffer_0_q0) > $signed(buffer_1_q0)) ? 1'b1 : 1'b0);

assign icmp_ln183_2_fu_641_p2 = (($signed(select_ln183_reg_758) > $signed(select_ln183_1_reg_764)) ? 1'b1 : 1'b0);

assign icmp_ln183_fu_596_p2 = (($signed(buffer_0_q1) > $signed(buffer_1_q1)) ? 1'b1 : 1'b0);

assign mx_fu_645_p3 = ((icmp_ln183_2_fu_641_p2[0:0] == 1'b1) ? select_ln183_reg_758 : select_ln183_1_reg_764);

assign or_ln_fu_452_p3 = {{trunc_ln179_fu_448_p1}, {4'd8}};

assign output_0_address0 = zext_ln185_2_fu_624_p1;

assign output_0_ce0 = output_0_ce0_local;

assign output_0_d0 = xor_ln61_fu_664_p2;

assign output_0_we0 = output_0_we0_local;

assign output_10_address0 = zext_ln185_2_fu_624_p1;

assign output_10_ce0 = output_10_ce0_local;

assign output_10_d0 = xor_ln61_fu_664_p2;

assign output_10_we0 = output_10_we0_local;

assign output_11_address0 = zext_ln185_2_fu_624_p1;

assign output_11_ce0 = output_11_ce0_local;

assign output_11_d0 = xor_ln61_fu_664_p2;

assign output_11_we0 = output_11_we0_local;

assign output_12_address0 = zext_ln185_2_fu_624_p1;

assign output_12_ce0 = output_12_ce0_local;

assign output_12_d0 = xor_ln61_fu_664_p2;

assign output_12_we0 = output_12_we0_local;

assign output_13_address0 = zext_ln185_2_fu_624_p1;

assign output_13_ce0 = output_13_ce0_local;

assign output_13_d0 = xor_ln61_fu_664_p2;

assign output_13_we0 = output_13_we0_local;

assign output_1_address0 = zext_ln185_2_fu_624_p1;

assign output_1_ce0 = output_1_ce0_local;

assign output_1_d0 = xor_ln61_fu_664_p2;

assign output_1_we0 = output_1_we0_local;

assign output_2_address0 = zext_ln185_2_fu_624_p1;

assign output_2_ce0 = output_2_ce0_local;

assign output_2_d0 = xor_ln61_fu_664_p2;

assign output_2_we0 = output_2_we0_local;

assign output_3_address0 = zext_ln185_2_fu_624_p1;

assign output_3_ce0 = output_3_ce0_local;

assign output_3_d0 = xor_ln61_fu_664_p2;

assign output_3_we0 = output_3_we0_local;

assign output_4_address0 = zext_ln185_2_fu_624_p1;

assign output_4_ce0 = output_4_ce0_local;

assign output_4_d0 = xor_ln61_fu_664_p2;

assign output_4_we0 = output_4_we0_local;

assign output_5_address0 = zext_ln185_2_fu_624_p1;

assign output_5_ce0 = output_5_ce0_local;

assign output_5_d0 = xor_ln61_fu_664_p2;

assign output_5_we0 = output_5_we0_local;

assign output_6_address0 = zext_ln185_2_fu_624_p1;

assign output_6_ce0 = output_6_ce0_local;

assign output_6_d0 = xor_ln61_fu_664_p2;

assign output_6_we0 = output_6_we0_local;

assign output_7_address0 = zext_ln185_2_fu_624_p1;

assign output_7_ce0 = output_7_ce0_local;

assign output_7_d0 = xor_ln61_fu_664_p2;

assign output_7_we0 = output_7_we0_local;

assign output_8_address0 = zext_ln185_2_fu_624_p1;

assign output_8_ce0 = output_8_ce0_local;

assign output_8_d0 = xor_ln61_fu_664_p2;

assign output_8_we0 = output_8_we0_local;

assign output_9_address0 = zext_ln185_2_fu_624_p1;

assign output_9_ce0 = output_9_ce0_local;

assign output_9_d0 = xor_ln61_fu_664_p2;

assign output_9_we0 = output_9_we0_local;

assign p_shl_fu_565_p3 = {{trunc_ln185_fu_561_p1}, {3'd0}};

assign select_ln140_read_reg_705 = select_ln140;

assign select_ln175_1_fu_440_p3 = ((icmp_ln176_fu_426_p2[0:0] == 1'b1) ? add_ln175_fu_420_p2 : ap_sig_allocacmp_oh_load);

assign select_ln175_fu_432_p3 = ((icmp_ln176_fu_426_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_ow_load);

assign select_ln183_1_fu_616_p3 = ((icmp_ln183_1_fu_610_p2[0:0] == 1'b1) ? buffer_0_q0 : buffer_1_q0);

assign select_ln183_fu_602_p3 = ((icmp_ln183_fu_596_p2[0:0] == 1'b1) ? buffer_0_q1 : buffer_1_q1);

assign sext_ln150_cast_fu_380_p1 = $signed(sext_ln150);

assign tmp_136_fu_656_p3 = val_fu_651_p2[32'd31];

assign tmp_fu_573_p3 = {{add_ln185_fu_555_p2}, {1'd0}};

assign tmp_s_fu_541_p3 = {{select_ln175_1_reg_728}, {3'd0}};

assign trunc_ln179_fu_448_p1 = select_ln175_1_fu_440_p3[2:0];

assign trunc_ln185_fu_561_p1 = add_ln185_fu_555_p2[6:0];

assign val_fu_651_p2 = ($signed(mx_fu_645_p3) + $signed(sext_ln150_cast_reg_714));

assign xor_ln61_fu_664_p2 = (tmp_136_fu_656_p3 ^ 1'd1);

assign zext_ln176_fu_460_p1 = select_ln175_fu_432_p3;

assign zext_ln179_1_fu_548_p1 = tmp_s_fu_541_p3;

assign zext_ln179_fu_472_p1 = add_ln_fu_464_p3;

assign zext_ln181_fu_484_p1 = add_ln181_fu_478_p2;

assign zext_ln185_1_fu_581_p1 = tmp_fu_573_p3;

assign zext_ln185_2_fu_624_p1 = add_ln185_1_reg_753;

assign zext_ln185_fu_552_p1 = select_ln175_reg_723;

endmodule //kernel_conv2d_l2_Pipeline_L2_FH_L2_FW
