-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity kernel_conv2d_l4_Pipeline_L4_KH_L4_KW is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    loc_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    zext_ln209 : IN STD_LOGIC_VECTOR (1 downto 0);
    zext_ln210 : IN STD_LOGIC_VECTOR (1 downto 0);
    udiv_ln2 : IN STD_LOGIC_VECTOR (8 downto 0);
    input_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    input_0_ce0 : OUT STD_LOGIC;
    input_0_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    input_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    input_1_ce0 : OUT STD_LOGIC;
    input_1_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    input_2_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    input_2_ce0 : OUT STD_LOGIC;
    input_2_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    input_3_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    input_3_ce0 : OUT STD_LOGIC;
    input_3_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    input_4_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    input_4_ce0 : OUT STD_LOGIC;
    input_4_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    input_5_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    input_5_ce0 : OUT STD_LOGIC;
    input_5_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    input_6_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    input_6_ce0 : OUT STD_LOGIC;
    input_6_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    input_7_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    input_7_ce0 : OUT STD_LOGIC;
    input_7_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    input_8_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    input_8_ce0 : OUT STD_LOGIC;
    input_8_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    input_9_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    input_9_ce0 : OUT STD_LOGIC;
    input_9_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    input_10_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    input_10_ce0 : OUT STD_LOGIC;
    input_10_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    input_11_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    input_11_ce0 : OUT STD_LOGIC;
    input_11_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    input_12_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    input_12_ce0 : OUT STD_LOGIC;
    input_12_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    input_13_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    input_13_ce0 : OUT STD_LOGIC;
    input_13_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    select_ln211 : IN STD_LOGIC_VECTOR (3 downto 0);
    kern_0_0_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_0_1_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_0_2_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_0_3_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_0_4_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_0_5_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_0_6_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_0_7_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_0_8_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_1_0_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_1_1_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_1_2_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_1_3_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_1_4_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_1_5_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_1_6_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_1_7_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_1_8_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_2_0_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_2_1_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_2_2_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_2_3_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_2_4_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_2_5_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_2_6_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_2_7_val : IN STD_LOGIC_VECTOR (0 downto 0);
    kern_2_8_val : IN STD_LOGIC_VECTOR (0 downto 0);
    k : IN STD_LOGIC_VECTOR (1 downto 0);
    loc_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    loc_3_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of kernel_conv2d_l4_Pipeline_L4_KH_L4_KW is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv9_13 : STD_LOGIC_VECTOR (8 downto 0) := "000010011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln214_fu_618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln210_cast_fu_587_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln210_cast_reg_1211 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln209_cast_fu_591_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln209_cast_reg_1216 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln214_reg_1221 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln214_reg_1221_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln214_reg_1221_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln214_reg_1221_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln214_reg_1221_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln211_1_fu_648_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln211_1_reg_1225 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln214_fu_656_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln214_reg_1231 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln218_fu_774_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln218_reg_1243 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln218_reg_1243_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln218_reg_1243_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln218_reg_1243_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln218_reg_1243_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_786_p21 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_1248 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_821_p21 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_1253 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_856_p21 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_1258 : STD_LOGIC_VECTOR (0 downto 0);
    signal w_fu_891_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal w_reg_1263 : STD_LOGIC_VECTOR (0 downto 0);
    signal w_reg_1263_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal w_reg_1263_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal w_reg_1263_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal a_fu_924_p31 : STD_LOGIC_VECTOR (0 downto 0);
    signal a_reg_1338 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln219_fu_907_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal loc_fu_184 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal loc_2_fu_1008_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal kw_fu_188 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal add_ln215_fu_664_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_kw_load : STD_LOGIC_VECTOR (1 downto 0);
    signal kh_fu_192 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_sig_allocacmp_kh_load : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten_fu_196 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln214_1_fu_624_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal input_0_ce0_local : STD_LOGIC;
    signal input_1_ce0_local : STD_LOGIC;
    signal input_2_ce0_local : STD_LOGIC;
    signal input_3_ce0_local : STD_LOGIC;
    signal input_4_ce0_local : STD_LOGIC;
    signal input_5_ce0_local : STD_LOGIC;
    signal input_6_ce0_local : STD_LOGIC;
    signal input_7_ce0_local : STD_LOGIC;
    signal input_8_ce0_local : STD_LOGIC;
    signal input_9_ce0_local : STD_LOGIC;
    signal input_10_ce0_local : STD_LOGIC;
    signal input_11_ce0_local : STD_LOGIC;
    signal input_12_ce0_local : STD_LOGIC;
    signal input_13_ce0_local : STD_LOGIC;
    signal icmp_ln215_fu_642_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln214_fu_636_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln217_fu_688_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln217_fu_693_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln217_1_fu_697_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_702_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl_fu_714_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln214_fu_685_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln217_2_fu_730_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln217_1_fu_735_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln217_3_fu_739_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln220_fu_710_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln219_fu_744_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln219_fu_748_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln218_fu_758_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_129_fu_764_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln215_fu_727_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln220_fu_721_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_786_p19 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln220_fu_780_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_821_p19 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_856_p19 : STD_LOGIC_VECTOR (0 downto 0);
    signal w_fu_891_p7 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln219_fu_907_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_1024_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal a_fu_924_p29 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln221_fu_990_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln221_fu_994_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal loc_3_fu_1002_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1024_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_fu_786_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_786_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_786_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_786_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_786_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_786_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_786_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_786_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_786_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_821_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_821_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_821_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_821_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_821_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_821_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_821_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_821_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_821_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_856_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_856_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_856_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_856_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_856_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_856_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_856_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_856_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_856_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal w_fu_891_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal w_fu_891_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal w_fu_891_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal a_fu_924_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal a_fu_924_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal a_fu_924_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal a_fu_924_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal a_fu_924_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal a_fu_924_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal a_fu_924_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal a_fu_924_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal a_fu_924_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal a_fu_924_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal a_fu_924_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal a_fu_924_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal a_fu_924_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal a_fu_924_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component kernel_sparsemux_19_4_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (3 downto 0);
        din8_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        din3 : IN STD_LOGIC_VECTOR (0 downto 0);
        din4 : IN STD_LOGIC_VECTOR (0 downto 0);
        din5 : IN STD_LOGIC_VECTOR (0 downto 0);
        din6 : IN STD_LOGIC_VECTOR (0 downto 0);
        din7 : IN STD_LOGIC_VECTOR (0 downto 0);
        din8 : IN STD_LOGIC_VECTOR (0 downto 0);
        def : IN STD_LOGIC_VECTOR (0 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component kernel_sparsemux_7_2_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        def : IN STD_LOGIC_VECTOR (0 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component kernel_sparsemux_29_4_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (3 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (3 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (3 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (3 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (3 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (3 downto 0);
        din13_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        din3 : IN STD_LOGIC_VECTOR (0 downto 0);
        din4 : IN STD_LOGIC_VECTOR (0 downto 0);
        din5 : IN STD_LOGIC_VECTOR (0 downto 0);
        din6 : IN STD_LOGIC_VECTOR (0 downto 0);
        din7 : IN STD_LOGIC_VECTOR (0 downto 0);
        din8 : IN STD_LOGIC_VECTOR (0 downto 0);
        din9 : IN STD_LOGIC_VECTOR (0 downto 0);
        din10 : IN STD_LOGIC_VECTOR (0 downto 0);
        din11 : IN STD_LOGIC_VECTOR (0 downto 0);
        din12 : IN STD_LOGIC_VECTOR (0 downto 0);
        din13 : IN STD_LOGIC_VECTOR (0 downto 0);
        def : IN STD_LOGIC_VECTOR (0 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component kernel_mac_muladd_8s_5ns_9s_9_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        din2 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_19_4_1_1_1_U98 : component kernel_sparsemux_19_4_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 1,
        CASE1 => "0001",
        din1_WIDTH => 1,
        CASE2 => "0010",
        din2_WIDTH => 1,
        CASE3 => "0011",
        din3_WIDTH => 1,
        CASE4 => "0100",
        din4_WIDTH => 1,
        CASE5 => "0101",
        din5_WIDTH => 1,
        CASE6 => "0110",
        din6_WIDTH => 1,
        CASE7 => "0111",
        din7_WIDTH => 1,
        CASE8 => "1000",
        din8_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 4,
        dout_WIDTH => 1)
    port map (
        din0 => kern_0_0_val,
        din1 => kern_0_1_val,
        din2 => kern_0_2_val,
        din3 => kern_0_3_val,
        din4 => kern_0_4_val,
        din5 => kern_0_5_val,
        din6 => kern_0_6_val,
        din7 => kern_0_7_val,
        din8 => kern_0_8_val,
        def => tmp_fu_786_p19,
        sel => add_ln220_fu_780_p2,
        dout => tmp_fu_786_p21);

    sparsemux_19_4_1_1_1_U99 : component kernel_sparsemux_19_4_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 1,
        CASE1 => "0001",
        din1_WIDTH => 1,
        CASE2 => "0010",
        din2_WIDTH => 1,
        CASE3 => "0011",
        din3_WIDTH => 1,
        CASE4 => "0100",
        din4_WIDTH => 1,
        CASE5 => "0101",
        din5_WIDTH => 1,
        CASE6 => "0110",
        din6_WIDTH => 1,
        CASE7 => "0111",
        din7_WIDTH => 1,
        CASE8 => "1000",
        din8_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 4,
        dout_WIDTH => 1)
    port map (
        din0 => kern_1_0_val,
        din1 => kern_1_1_val,
        din2 => kern_1_2_val,
        din3 => kern_1_3_val,
        din4 => kern_1_4_val,
        din5 => kern_1_5_val,
        din6 => kern_1_6_val,
        din7 => kern_1_7_val,
        din8 => kern_1_8_val,
        def => tmp_s_fu_821_p19,
        sel => add_ln220_fu_780_p2,
        dout => tmp_s_fu_821_p21);

    sparsemux_19_4_1_1_1_U100 : component kernel_sparsemux_19_4_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 1,
        CASE1 => "0001",
        din1_WIDTH => 1,
        CASE2 => "0010",
        din2_WIDTH => 1,
        CASE3 => "0011",
        din3_WIDTH => 1,
        CASE4 => "0100",
        din4_WIDTH => 1,
        CASE5 => "0101",
        din5_WIDTH => 1,
        CASE6 => "0110",
        din6_WIDTH => 1,
        CASE7 => "0111",
        din7_WIDTH => 1,
        CASE8 => "1000",
        din8_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 4,
        dout_WIDTH => 1)
    port map (
        din0 => kern_2_0_val,
        din1 => kern_2_1_val,
        din2 => kern_2_2_val,
        din3 => kern_2_3_val,
        din4 => kern_2_4_val,
        din5 => kern_2_5_val,
        din6 => kern_2_6_val,
        din7 => kern_2_7_val,
        din8 => kern_2_8_val,
        def => tmp_4_fu_856_p19,
        sel => add_ln220_fu_780_p2,
        dout => tmp_4_fu_856_p21);

    sparsemux_7_2_1_1_1_U101 : component kernel_sparsemux_7_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "10",
        din2_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => tmp_reg_1248,
        din1 => tmp_s_reg_1253,
        din2 => tmp_4_reg_1258,
        def => w_fu_891_p7,
        sel => k,
        dout => w_fu_891_p9);

    sparsemux_29_4_1_1_1_U102 : component kernel_sparsemux_29_4_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 1,
        CASE1 => "0001",
        din1_WIDTH => 1,
        CASE2 => "0010",
        din2_WIDTH => 1,
        CASE3 => "0011",
        din3_WIDTH => 1,
        CASE4 => "0100",
        din4_WIDTH => 1,
        CASE5 => "0101",
        din5_WIDTH => 1,
        CASE6 => "0110",
        din6_WIDTH => 1,
        CASE7 => "0111",
        din7_WIDTH => 1,
        CASE8 => "1000",
        din8_WIDTH => 1,
        CASE9 => "1001",
        din9_WIDTH => 1,
        CASE10 => "1010",
        din10_WIDTH => 1,
        CASE11 => "1011",
        din11_WIDTH => 1,
        CASE12 => "1100",
        din12_WIDTH => 1,
        CASE13 => "1101",
        din13_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 4,
        dout_WIDTH => 1)
    port map (
        din0 => input_0_q0,
        din1 => input_1_q0,
        din2 => input_2_q0,
        din3 => input_3_q0,
        din4 => input_4_q0,
        din5 => input_5_q0,
        din6 => input_6_q0,
        din7 => input_7_q0,
        din8 => input_8_q0,
        din9 => input_9_q0,
        din10 => input_10_q0,
        din11 => input_11_q0,
        din12 => input_12_q0,
        din13 => input_13_q0,
        def => a_fu_924_p29,
        sel => select_ln211,
        dout => a_fu_924_p31);

    mac_muladd_8s_5ns_9s_9_4_1_U103 : component kernel_mac_muladd_8s_5ns_9s_9_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        din2_WIDTH => 9,
        dout_WIDTH => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => add_ln219_fu_748_p2,
        din1 => grp_fu_1024_p1,
        din2 => udiv_ln2,
        ce => ap_const_logic_1,
        dout => grp_fu_1024_p3);

    flow_control_loop_pipe_sequential_init_U : component kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_fu_196_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln214_fu_618_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_196 <= add_ln214_1_fu_624_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_196 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    kh_fu_192_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln214_fu_618_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    kh_fu_192 <= select_ln214_fu_656_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    kh_fu_192 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    kw_fu_188_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln214_fu_618_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    kw_fu_188 <= add_ln215_fu_664_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    kw_fu_188 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    loc_fu_184_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    loc_fu_184 <= loc_1;
                elsif ((ap_enable_reg_pp0_iter6 = ap_const_logic_1)) then 
                    loc_fu_184 <= loc_2_fu_1008_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                a_reg_1338 <= a_fu_924_p31;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                icmp_ln214_reg_1221_pp0_iter2_reg <= icmp_ln214_reg_1221_pp0_iter1_reg;
                icmp_ln214_reg_1221_pp0_iter3_reg <= icmp_ln214_reg_1221_pp0_iter2_reg;
                icmp_ln214_reg_1221_pp0_iter4_reg <= icmp_ln214_reg_1221_pp0_iter3_reg;
                icmp_ln218_reg_1243_pp0_iter2_reg <= icmp_ln218_reg_1243;
                icmp_ln218_reg_1243_pp0_iter3_reg <= icmp_ln218_reg_1243_pp0_iter2_reg;
                icmp_ln218_reg_1243_pp0_iter4_reg <= icmp_ln218_reg_1243_pp0_iter3_reg;
                icmp_ln218_reg_1243_pp0_iter5_reg <= icmp_ln218_reg_1243_pp0_iter4_reg;
                w_reg_1263 <= w_fu_891_p9;
                w_reg_1263_pp0_iter3_reg <= w_reg_1263;
                w_reg_1263_pp0_iter4_reg <= w_reg_1263_pp0_iter3_reg;
                w_reg_1263_pp0_iter5_reg <= w_reg_1263_pp0_iter4_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln214_reg_1221 <= icmp_ln214_fu_618_p2;
                icmp_ln214_reg_1221_pp0_iter1_reg <= icmp_ln214_reg_1221;
                icmp_ln218_reg_1243 <= icmp_ln218_fu_774_p2;
                select_ln211_1_reg_1225 <= select_ln211_1_fu_648_p3;
                select_ln214_reg_1231 <= select_ln214_fu_656_p3;
                tmp_4_reg_1258 <= tmp_4_fu_856_p21;
                tmp_reg_1248 <= tmp_fu_786_p21;
                tmp_s_reg_1253 <= tmp_s_fu_821_p21;
                    zext_ln209_cast_reg_1216(1 downto 0) <= zext_ln209_cast_fu_591_p1(1 downto 0);
                    zext_ln210_cast_reg_1211(1 downto 0) <= zext_ln210_cast_fu_587_p1(1 downto 0);
            end if;
        end if;
    end process;
    zext_ln210_cast_reg_1211(3 downto 2) <= "00";
    zext_ln209_cast_reg_1216(3 downto 2) <= "00";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    a_fu_924_p29 <= "X";
    add_ln214_1_fu_624_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv4_1));
    add_ln214_fu_636_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_kh_load) + unsigned(ap_const_lv2_1));
    add_ln215_fu_664_p2 <= std_logic_vector(unsigned(select_ln211_1_fu_648_p3) + unsigned(ap_const_lv2_1));
    add_ln217_1_fu_697_p2 <= std_logic_vector(signed(sext_ln217_fu_693_p1) + signed(zext_ln209_cast_reg_1216));
    add_ln217_2_fu_730_p2 <= std_logic_vector(unsigned(select_ln211_1_reg_1225) + unsigned(ap_const_lv2_3));
    add_ln217_3_fu_739_p2 <= std_logic_vector(signed(sext_ln217_1_fu_735_p1) + signed(zext_ln210_cast_reg_1211));
    add_ln217_fu_688_p2 <= std_logic_vector(unsigned(select_ln214_reg_1231) + unsigned(ap_const_lv2_3));
    add_ln219_fu_748_p2 <= std_logic_vector(unsigned(zext_ln220_fu_710_p1) + unsigned(sext_ln219_fu_744_p1));
    add_ln220_fu_780_p2 <= std_logic_vector(unsigned(zext_ln215_fu_727_p1) + unsigned(sub_ln220_fu_721_p2));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln214_fu_618_p2)
    begin
        if (((icmp_ln214_fu_618_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter5_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_196)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_196;
        end if; 
    end process;


    ap_sig_allocacmp_kh_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, kh_fu_192)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_kh_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_kh_load <= kh_fu_192;
        end if; 
    end process;


    ap_sig_allocacmp_kw_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, kw_fu_188)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_kw_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_kw_load <= kw_fu_188;
        end if; 
    end process;

    grp_fu_1024_p1 <= ap_const_lv9_13(5 - 1 downto 0);
    icmp_ln214_fu_618_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv4_9) else "0";
    icmp_ln215_fu_642_p2 <= "1" when (ap_sig_allocacmp_kw_load = ap_const_lv2_3) else "0";
    icmp_ln218_fu_774_p2 <= "1" when (tmp_129_fu_764_p4 = ap_const_lv2_0) else "0";
    input_0_address0 <= zext_ln219_fu_907_p1(9 - 1 downto 0);
    input_0_ce0 <= input_0_ce0_local;

    input_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            input_0_ce0_local <= ap_const_logic_1;
        else 
            input_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_10_address0 <= zext_ln219_fu_907_p1(9 - 1 downto 0);
    input_10_ce0 <= input_10_ce0_local;

    input_10_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            input_10_ce0_local <= ap_const_logic_1;
        else 
            input_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_11_address0 <= zext_ln219_fu_907_p1(9 - 1 downto 0);
    input_11_ce0 <= input_11_ce0_local;

    input_11_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            input_11_ce0_local <= ap_const_logic_1;
        else 
            input_11_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_12_address0 <= zext_ln219_fu_907_p1(9 - 1 downto 0);
    input_12_ce0 <= input_12_ce0_local;

    input_12_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            input_12_ce0_local <= ap_const_logic_1;
        else 
            input_12_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_13_address0 <= zext_ln219_fu_907_p1(9 - 1 downto 0);
    input_13_ce0 <= input_13_ce0_local;

    input_13_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            input_13_ce0_local <= ap_const_logic_1;
        else 
            input_13_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_1_address0 <= zext_ln219_fu_907_p1(9 - 1 downto 0);
    input_1_ce0 <= input_1_ce0_local;

    input_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            input_1_ce0_local <= ap_const_logic_1;
        else 
            input_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_2_address0 <= zext_ln219_fu_907_p1(9 - 1 downto 0);
    input_2_ce0 <= input_2_ce0_local;

    input_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            input_2_ce0_local <= ap_const_logic_1;
        else 
            input_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_3_address0 <= zext_ln219_fu_907_p1(9 - 1 downto 0);
    input_3_ce0 <= input_3_ce0_local;

    input_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            input_3_ce0_local <= ap_const_logic_1;
        else 
            input_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_4_address0 <= zext_ln219_fu_907_p1(9 - 1 downto 0);
    input_4_ce0 <= input_4_ce0_local;

    input_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            input_4_ce0_local <= ap_const_logic_1;
        else 
            input_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_5_address0 <= zext_ln219_fu_907_p1(9 - 1 downto 0);
    input_5_ce0 <= input_5_ce0_local;

    input_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            input_5_ce0_local <= ap_const_logic_1;
        else 
            input_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_6_address0 <= zext_ln219_fu_907_p1(9 - 1 downto 0);
    input_6_ce0 <= input_6_ce0_local;

    input_6_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            input_6_ce0_local <= ap_const_logic_1;
        else 
            input_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_7_address0 <= zext_ln219_fu_907_p1(9 - 1 downto 0);
    input_7_ce0 <= input_7_ce0_local;

    input_7_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            input_7_ce0_local <= ap_const_logic_1;
        else 
            input_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_8_address0 <= zext_ln219_fu_907_p1(9 - 1 downto 0);
    input_8_ce0 <= input_8_ce0_local;

    input_8_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            input_8_ce0_local <= ap_const_logic_1;
        else 
            input_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_9_address0 <= zext_ln219_fu_907_p1(9 - 1 downto 0);
    input_9_ce0 <= input_9_ce0_local;

    input_9_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            input_9_ce0_local <= ap_const_logic_1;
        else 
            input_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    loc_2_fu_1008_p3 <= 
        loc_3_fu_1002_p2 when (icmp_ln218_reg_1243_pp0_iter5_reg(0) = '1') else 
        loc_fu_184;
    loc_3_fu_1002_p2 <= std_logic_vector(unsigned(select_ln221_fu_994_p3) + unsigned(loc_fu_184));
    loc_3_out <= loc_fu_184;

    loc_3_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln214_reg_1221_pp0_iter4_reg, ap_loop_exit_ready_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1) and (icmp_ln214_reg_1221_pp0_iter4_reg = ap_const_lv1_1))) then 
            loc_3_out_ap_vld <= ap_const_logic_1;
        else 
            loc_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    or_ln218_fu_758_p2 <= (add_ln217_3_fu_739_p2 or add_ln217_1_fu_697_p2);
    p_shl_fu_714_p3 <= (select_ln214_reg_1231 & ap_const_lv2_0);
    select_ln211_1_fu_648_p3 <= 
        ap_const_lv2_0 when (icmp_ln215_fu_642_p2(0) = '1') else 
        ap_sig_allocacmp_kw_load;
    select_ln214_fu_656_p3 <= 
        add_ln214_fu_636_p2 when (icmp_ln215_fu_642_p2(0) = '1') else 
        ap_sig_allocacmp_kh_load;
    select_ln221_fu_994_p3 <= 
        ap_const_lv32_FFFFFFFF when (xor_ln221_fu_990_p2(0) = '1') else 
        ap_const_lv32_1;
        sext_ln217_1_fu_735_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln217_2_fu_730_p2),4));

        sext_ln217_fu_693_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln217_fu_688_p2),4));

        sext_ln219_fu_744_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln217_3_fu_739_p2),8));

    sub_ln220_fu_721_p2 <= std_logic_vector(unsigned(p_shl_fu_714_p3) - unsigned(zext_ln214_fu_685_p1));
    tmp_129_fu_764_p4 <= or_ln218_fu_758_p2(3 downto 2);
    tmp_3_fu_702_p3 <= (add_ln217_1_fu_697_p2 & ap_const_lv2_0);
    tmp_4_fu_856_p19 <= "X";
    tmp_fu_786_p19 <= "X";
    tmp_s_fu_821_p19 <= "X";
    w_fu_891_p7 <= "X";
    xor_ln221_fu_990_p2 <= (w_reg_1263_pp0_iter5_reg xor a_reg_1338);
    zext_ln209_cast_fu_591_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln209),4));
    zext_ln210_cast_fu_587_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln210),4));
    zext_ln214_fu_685_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln214_reg_1231),4));
    zext_ln215_fu_727_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln211_1_reg_1225),4));
    zext_ln219_fu_907_p0 <= grp_fu_1024_p3;
    zext_ln219_fu_907_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln219_fu_907_p0),64));
    zext_ln220_fu_710_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_702_p3),8));
end behav;
