-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity kernel_conv2d_l3_Pipeline_L3_FH_L3_FW is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    zext_ln199 : IN STD_LOGIC_VECTOR (8 downto 0);
    output_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_0_ce0 : OUT STD_LOGIC;
    output_0_we0 : OUT STD_LOGIC;
    output_0_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_1_ce0 : OUT STD_LOGIC;
    output_1_we0 : OUT STD_LOGIC;
    output_1_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_2_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_2_ce0 : OUT STD_LOGIC;
    output_2_we0 : OUT STD_LOGIC;
    output_2_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_3_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_3_ce0 : OUT STD_LOGIC;
    output_3_we0 : OUT STD_LOGIC;
    output_3_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_4_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_4_ce0 : OUT STD_LOGIC;
    output_4_we0 : OUT STD_LOGIC;
    output_4_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_5_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_5_ce0 : OUT STD_LOGIC;
    output_5_we0 : OUT STD_LOGIC;
    output_5_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_6_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_6_ce0 : OUT STD_LOGIC;
    output_6_we0 : OUT STD_LOGIC;
    output_6_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_7_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_7_ce0 : OUT STD_LOGIC;
    output_7_we0 : OUT STD_LOGIC;
    output_7_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_8_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_8_ce0 : OUT STD_LOGIC;
    output_8_we0 : OUT STD_LOGIC;
    output_8_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_9_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_9_ce0 : OUT STD_LOGIC;
    output_9_we0 : OUT STD_LOGIC;
    output_9_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_10_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_10_ce0 : OUT STD_LOGIC;
    output_10_we0 : OUT STD_LOGIC;
    output_10_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_11_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_11_ce0 : OUT STD_LOGIC;
    output_11_we0 : OUT STD_LOGIC;
    output_11_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_12_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_12_ce0 : OUT STD_LOGIC;
    output_12_we0 : OUT STD_LOGIC;
    output_12_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_13_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_13_ce0 : OUT STD_LOGIC;
    output_13_we0 : OUT STD_LOGIC;
    output_13_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    buffer_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    buffer_1_ce0 : OUT STD_LOGIC;
    buffer_1_we0 : OUT STD_LOGIC;
    buffer_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    buffer_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    buffer_1_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    buffer_1_ce1 : OUT STD_LOGIC;
    buffer_1_we1 : OUT STD_LOGIC;
    buffer_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    buffer_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    buffer_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    buffer_0_ce0 : OUT STD_LOGIC;
    buffer_0_we0 : OUT STD_LOGIC;
    buffer_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    buffer_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    buffer_0_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    buffer_0_ce1 : OUT STD_LOGIC;
    buffer_0_we1 : OUT STD_LOGIC;
    buffer_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    buffer_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    sext_ln209 : IN STD_LOGIC_VECTOR (15 downto 0);
    select_ln199 : IN STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of kernel_conv2d_l3_Pipeline_L3_FH_L3_FW is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv9_13 : STD_LOGIC_VECTOR (8 downto 0) := "000010011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln234_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal select_ln199_read_reg_677 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sext_ln209_cast_fu_382_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln209_cast_reg_686 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln242_fu_565_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln242_reg_715 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln242_1_fu_579_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln242_1_reg_721 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_reg_727 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln238_fu_490_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln240_fu_502_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln244_2_fu_610_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ow_fu_116 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln235_fu_538_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_ow_load : STD_LOGIC_VECTOR (2 downto 0);
    signal oh_fu_120 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal select_ln234_1_fu_442_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_oh_load : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten6_fu_124 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln234_1_fu_410_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_indvar_flatten6_load : STD_LOGIC_VECTOR (4 downto 0);
    signal buffer_0_ce1_local : STD_LOGIC;
    signal buffer_0_ce0_local : STD_LOGIC;
    signal buffer_0_we1_local : STD_LOGIC;
    signal buffer_0_we0_local : STD_LOGIC;
    signal buffer_1_ce1_local : STD_LOGIC;
    signal buffer_1_ce0_local : STD_LOGIC;
    signal buffer_1_we1_local : STD_LOGIC;
    signal buffer_1_we0_local : STD_LOGIC;
    signal output_12_we0_local : STD_LOGIC;
    signal xor_ln61_fu_627_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal output_12_ce0_local : STD_LOGIC;
    signal output_11_we0_local : STD_LOGIC;
    signal output_11_ce0_local : STD_LOGIC;
    signal output_10_we0_local : STD_LOGIC;
    signal output_10_ce0_local : STD_LOGIC;
    signal output_9_we0_local : STD_LOGIC;
    signal output_9_ce0_local : STD_LOGIC;
    signal output_8_we0_local : STD_LOGIC;
    signal output_8_ce0_local : STD_LOGIC;
    signal output_7_we0_local : STD_LOGIC;
    signal output_7_ce0_local : STD_LOGIC;
    signal output_6_we0_local : STD_LOGIC;
    signal output_6_ce0_local : STD_LOGIC;
    signal output_5_we0_local : STD_LOGIC;
    signal output_5_ce0_local : STD_LOGIC;
    signal output_4_we0_local : STD_LOGIC;
    signal output_4_ce0_local : STD_LOGIC;
    signal output_3_we0_local : STD_LOGIC;
    signal output_3_ce0_local : STD_LOGIC;
    signal output_2_we0_local : STD_LOGIC;
    signal output_2_ce0_local : STD_LOGIC;
    signal output_1_we0_local : STD_LOGIC;
    signal output_1_ce0_local : STD_LOGIC;
    signal output_0_we0_local : STD_LOGIC;
    signal output_0_ce0_local : STD_LOGIC;
    signal output_13_we0_local : STD_LOGIC;
    signal output_13_ce0_local : STD_LOGIC;
    signal icmp_ln235_fu_428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln234_fu_422_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_450_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln238_fu_462_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln234_fu_434_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln_fu_482_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln235_fu_478_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln_fu_466_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln240_fu_496_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln242_fu_559_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln242_1_fu_573_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln242_2_fu_587_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal mx_fu_591_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_fu_597_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_646_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_646_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_646_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_646_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_646_p00 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_646_p10 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component kernel_ama_addmuladd_5ns_3ns_5ns_9s_9_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        din2 : IN STD_LOGIC_VECTOR (4 downto 0);
        din3 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    ama_addmuladd_5ns_3ns_5ns_9s_9_4_1_U296 : component kernel_ama_addmuladd_5ns_3ns_5ns_9s_9_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 5,
        din1_WIDTH => 3,
        din2_WIDTH => 5,
        din3_WIDTH => 9,
        dout_WIDTH => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_646_p0,
        din1 => grp_fu_646_p1,
        din2 => grp_fu_646_p2,
        din3 => zext_ln199,
        ce => ap_const_logic_1,
        dout => grp_fu_646_p4);

    flow_control_loop_pipe_sequential_init_U : component kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten6_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln234_fu_404_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten6_fu_124 <= add_ln234_1_fu_410_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten6_fu_124 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    oh_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln234_fu_404_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    oh_fu_120 <= select_ln234_1_fu_442_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    oh_fu_120 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    ow_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln234_fu_404_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    ow_fu_116 <= add_ln235_fu_538_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    ow_fu_116 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                select_ln242_1_reg_721 <= select_ln242_1_fu_579_p3;
                select_ln242_reg_715 <= select_ln242_fu_565_p3;
                sext_ln209_cast_reg_686 <= sext_ln209_cast_fu_382_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                tmp_reg_727 <= val_fu_597_p2(31 downto 31);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln234_1_fu_410_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten6_load) + unsigned(ap_const_lv5_1));
    add_ln234_fu_422_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_oh_load) + unsigned(ap_const_lv3_1));
    add_ln235_fu_538_p2 <= std_logic_vector(unsigned(select_ln234_fu_434_p3) + unsigned(ap_const_lv3_1));
    add_ln240_fu_496_p2 <= std_logic_vector(unsigned(zext_ln235_fu_478_p1) + unsigned(or_ln_fu_466_p3));
    add_ln_fu_482_p3 <= (trunc_ln238_fu_462_p1 & select_ln234_fu_434_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln234_fu_404_p2)
    begin
        if (((icmp_ln234_fu_404_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten6_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten6_fu_124)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten6_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_indvar_flatten6_load <= indvar_flatten6_fu_124;
        end if; 
    end process;


    ap_sig_allocacmp_oh_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, oh_fu_120)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_oh_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_oh_load <= oh_fu_120;
        end if; 
    end process;


    ap_sig_allocacmp_ow_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ow_fu_116, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_ow_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_ow_load <= ow_fu_116;
        end if; 
    end process;

    buffer_0_address0 <= zext_ln240_fu_502_p1(9 - 1 downto 0);
    buffer_0_address1 <= zext_ln238_fu_490_p1(9 - 1 downto 0);
    buffer_0_ce0 <= buffer_0_ce0_local;

    buffer_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln234_fu_404_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln234_fu_404_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_0_ce0_local <= ap_const_logic_1;
        else 
            buffer_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buffer_0_ce1 <= buffer_0_ce1_local;

    buffer_0_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln234_fu_404_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln234_fu_404_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_0_ce1_local <= ap_const_logic_1;
        else 
            buffer_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    buffer_0_d0 <= ap_const_lv32_0;
    buffer_0_d1 <= ap_const_lv32_0;
    buffer_0_we0 <= buffer_0_we0_local;

    buffer_0_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln234_fu_404_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln234_fu_404_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_0_we0_local <= ap_const_logic_1;
        else 
            buffer_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    buffer_0_we1 <= buffer_0_we1_local;

    buffer_0_we1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln234_fu_404_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln234_fu_404_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_0_we1_local <= ap_const_logic_1;
        else 
            buffer_0_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    buffer_1_address0 <= zext_ln240_fu_502_p1(9 - 1 downto 0);
    buffer_1_address1 <= zext_ln238_fu_490_p1(9 - 1 downto 0);
    buffer_1_ce0 <= buffer_1_ce0_local;

    buffer_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln234_fu_404_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln234_fu_404_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_1_ce0_local <= ap_const_logic_1;
        else 
            buffer_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buffer_1_ce1 <= buffer_1_ce1_local;

    buffer_1_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln234_fu_404_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln234_fu_404_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_1_ce1_local <= ap_const_logic_1;
        else 
            buffer_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    buffer_1_d0 <= ap_const_lv32_0;
    buffer_1_d1 <= ap_const_lv32_0;
    buffer_1_we0 <= buffer_1_we0_local;

    buffer_1_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln234_fu_404_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln234_fu_404_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_1_we0_local <= ap_const_logic_1;
        else 
            buffer_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    buffer_1_we1 <= buffer_1_we1_local;

    buffer_1_we1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln234_fu_404_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln234_fu_404_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_1_we1_local <= ap_const_logic_1;
        else 
            buffer_1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_646_p0 <= grp_fu_646_p00(5 - 1 downto 0);
    grp_fu_646_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_450_p3),6));
    grp_fu_646_p1 <= grp_fu_646_p10(3 - 1 downto 0);
    grp_fu_646_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln234_fu_434_p3),6));
    grp_fu_646_p2 <= ap_const_lv9_13(5 - 1 downto 0);
    icmp_ln234_fu_404_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten6_load = ap_const_lv5_10) else "0";
    icmp_ln235_fu_428_p2 <= "1" when (ap_sig_allocacmp_ow_load = ap_const_lv3_4) else "0";
    icmp_ln242_1_fu_573_p2 <= "1" when (signed(buffer_0_q0) > signed(buffer_1_q0)) else "0";
    icmp_ln242_2_fu_587_p2 <= "1" when (signed(select_ln242_reg_715) > signed(select_ln242_1_reg_721)) else "0";
    icmp_ln242_fu_559_p2 <= "1" when (signed(buffer_0_q1) > signed(buffer_1_q1)) else "0";
    mx_fu_591_p3 <= 
        select_ln242_reg_715 when (icmp_ln242_2_fu_587_p2(0) = '1') else 
        select_ln242_1_reg_721;
    or_ln_fu_466_p3 <= (trunc_ln238_fu_462_p1 & ap_const_lv3_4);
    output_0_address0 <= zext_ln244_2_fu_610_p1(9 - 1 downto 0);
    output_0_ce0 <= output_0_ce0_local;

    output_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            output_0_ce0_local <= ap_const_logic_1;
        else 
            output_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_0_d0 <= xor_ln61_fu_627_p2;
    output_0_we0 <= output_0_we0_local;

    output_0_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, select_ln199_read_reg_677, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (select_ln199_read_reg_677 = ap_const_lv4_0))) then 
            output_0_we0_local <= ap_const_logic_1;
        else 
            output_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_10_address0 <= zext_ln244_2_fu_610_p1(9 - 1 downto 0);
    output_10_ce0 <= output_10_ce0_local;

    output_10_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            output_10_ce0_local <= ap_const_logic_1;
        else 
            output_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_10_d0 <= xor_ln61_fu_627_p2;
    output_10_we0 <= output_10_we0_local;

    output_10_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, select_ln199_read_reg_677, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (select_ln199_read_reg_677 = ap_const_lv4_A))) then 
            output_10_we0_local <= ap_const_logic_1;
        else 
            output_10_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_11_address0 <= zext_ln244_2_fu_610_p1(9 - 1 downto 0);
    output_11_ce0 <= output_11_ce0_local;

    output_11_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            output_11_ce0_local <= ap_const_logic_1;
        else 
            output_11_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_11_d0 <= xor_ln61_fu_627_p2;
    output_11_we0 <= output_11_we0_local;

    output_11_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, select_ln199_read_reg_677, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (select_ln199_read_reg_677 = ap_const_lv4_B))) then 
            output_11_we0_local <= ap_const_logic_1;
        else 
            output_11_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_12_address0 <= zext_ln244_2_fu_610_p1(9 - 1 downto 0);
    output_12_ce0 <= output_12_ce0_local;

    output_12_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            output_12_ce0_local <= ap_const_logic_1;
        else 
            output_12_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_12_d0 <= xor_ln61_fu_627_p2;
    output_12_we0 <= output_12_we0_local;

    output_12_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, select_ln199_read_reg_677, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (select_ln199_read_reg_677 = ap_const_lv4_C))) then 
            output_12_we0_local <= ap_const_logic_1;
        else 
            output_12_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_13_address0 <= zext_ln244_2_fu_610_p1(9 - 1 downto 0);
    output_13_ce0 <= output_13_ce0_local;

    output_13_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            output_13_ce0_local <= ap_const_logic_1;
        else 
            output_13_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_13_d0 <= xor_ln61_fu_627_p2;
    output_13_we0 <= output_13_we0_local;

    output_13_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, select_ln199_read_reg_677, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and ((select_ln199_read_reg_677 = ap_const_lv4_D) or ((select_ln199_read_reg_677 = ap_const_lv4_E) or (select_ln199_read_reg_677 = ap_const_lv4_F))))) then 
            output_13_we0_local <= ap_const_logic_1;
        else 
            output_13_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_1_address0 <= zext_ln244_2_fu_610_p1(9 - 1 downto 0);
    output_1_ce0 <= output_1_ce0_local;

    output_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            output_1_ce0_local <= ap_const_logic_1;
        else 
            output_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_1_d0 <= xor_ln61_fu_627_p2;
    output_1_we0 <= output_1_we0_local;

    output_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, select_ln199_read_reg_677, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (select_ln199_read_reg_677 = ap_const_lv4_1))) then 
            output_1_we0_local <= ap_const_logic_1;
        else 
            output_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_2_address0 <= zext_ln244_2_fu_610_p1(9 - 1 downto 0);
    output_2_ce0 <= output_2_ce0_local;

    output_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            output_2_ce0_local <= ap_const_logic_1;
        else 
            output_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_2_d0 <= xor_ln61_fu_627_p2;
    output_2_we0 <= output_2_we0_local;

    output_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, select_ln199_read_reg_677, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (select_ln199_read_reg_677 = ap_const_lv4_2))) then 
            output_2_we0_local <= ap_const_logic_1;
        else 
            output_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_3_address0 <= zext_ln244_2_fu_610_p1(9 - 1 downto 0);
    output_3_ce0 <= output_3_ce0_local;

    output_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            output_3_ce0_local <= ap_const_logic_1;
        else 
            output_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_3_d0 <= xor_ln61_fu_627_p2;
    output_3_we0 <= output_3_we0_local;

    output_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, select_ln199_read_reg_677, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (select_ln199_read_reg_677 = ap_const_lv4_3))) then 
            output_3_we0_local <= ap_const_logic_1;
        else 
            output_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_4_address0 <= zext_ln244_2_fu_610_p1(9 - 1 downto 0);
    output_4_ce0 <= output_4_ce0_local;

    output_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            output_4_ce0_local <= ap_const_logic_1;
        else 
            output_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_4_d0 <= xor_ln61_fu_627_p2;
    output_4_we0 <= output_4_we0_local;

    output_4_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, select_ln199_read_reg_677, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (select_ln199_read_reg_677 = ap_const_lv4_4))) then 
            output_4_we0_local <= ap_const_logic_1;
        else 
            output_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_5_address0 <= zext_ln244_2_fu_610_p1(9 - 1 downto 0);
    output_5_ce0 <= output_5_ce0_local;

    output_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            output_5_ce0_local <= ap_const_logic_1;
        else 
            output_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_5_d0 <= xor_ln61_fu_627_p2;
    output_5_we0 <= output_5_we0_local;

    output_5_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, select_ln199_read_reg_677, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (select_ln199_read_reg_677 = ap_const_lv4_5))) then 
            output_5_we0_local <= ap_const_logic_1;
        else 
            output_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_6_address0 <= zext_ln244_2_fu_610_p1(9 - 1 downto 0);
    output_6_ce0 <= output_6_ce0_local;

    output_6_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            output_6_ce0_local <= ap_const_logic_1;
        else 
            output_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_6_d0 <= xor_ln61_fu_627_p2;
    output_6_we0 <= output_6_we0_local;

    output_6_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, select_ln199_read_reg_677, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (select_ln199_read_reg_677 = ap_const_lv4_6))) then 
            output_6_we0_local <= ap_const_logic_1;
        else 
            output_6_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_7_address0 <= zext_ln244_2_fu_610_p1(9 - 1 downto 0);
    output_7_ce0 <= output_7_ce0_local;

    output_7_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            output_7_ce0_local <= ap_const_logic_1;
        else 
            output_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_7_d0 <= xor_ln61_fu_627_p2;
    output_7_we0 <= output_7_we0_local;

    output_7_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, select_ln199_read_reg_677, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (select_ln199_read_reg_677 = ap_const_lv4_7))) then 
            output_7_we0_local <= ap_const_logic_1;
        else 
            output_7_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_8_address0 <= zext_ln244_2_fu_610_p1(9 - 1 downto 0);
    output_8_ce0 <= output_8_ce0_local;

    output_8_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            output_8_ce0_local <= ap_const_logic_1;
        else 
            output_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_8_d0 <= xor_ln61_fu_627_p2;
    output_8_we0 <= output_8_we0_local;

    output_8_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, select_ln199_read_reg_677, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (select_ln199_read_reg_677 = ap_const_lv4_8))) then 
            output_8_we0_local <= ap_const_logic_1;
        else 
            output_8_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_9_address0 <= zext_ln244_2_fu_610_p1(9 - 1 downto 0);
    output_9_ce0 <= output_9_ce0_local;

    output_9_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            output_9_ce0_local <= ap_const_logic_1;
        else 
            output_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_9_d0 <= xor_ln61_fu_627_p2;
    output_9_we0 <= output_9_we0_local;

    output_9_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, select_ln199_read_reg_677, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (select_ln199_read_reg_677 = ap_const_lv4_9))) then 
            output_9_we0_local <= ap_const_logic_1;
        else 
            output_9_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln199_read_reg_677 <= select_ln199;
    select_ln234_1_fu_442_p3 <= 
        add_ln234_fu_422_p2 when (icmp_ln235_fu_428_p2(0) = '1') else 
        ap_sig_allocacmp_oh_load;
    select_ln234_fu_434_p3 <= 
        ap_const_lv3_0 when (icmp_ln235_fu_428_p2(0) = '1') else 
        ap_sig_allocacmp_ow_load;
    select_ln242_1_fu_579_p3 <= 
        buffer_0_q0 when (icmp_ln242_1_fu_573_p2(0) = '1') else 
        buffer_1_q0;
    select_ln242_fu_565_p3 <= 
        buffer_0_q1 when (icmp_ln242_fu_559_p2(0) = '1') else 
        buffer_1_q1;
        sext_ln209_cast_fu_382_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln209),32));

    tmp_s_fu_450_p3 <= (select_ln234_1_fu_442_p3 & ap_const_lv2_0);
    trunc_ln238_fu_462_p1 <= select_ln234_1_fu_442_p3(2 - 1 downto 0);
    val_fu_597_p2 <= std_logic_vector(unsigned(mx_fu_591_p3) + unsigned(sext_ln209_cast_reg_686));
    xor_ln61_fu_627_p2 <= (tmp_reg_727 xor ap_const_lv1_1);
    zext_ln235_fu_478_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln234_fu_434_p3),5));
    zext_ln238_fu_490_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln_fu_482_p3),64));
    zext_ln240_fu_502_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln240_fu_496_p2),64));
    zext_ln244_2_fu_610_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_646_p4),64));
end behav;
